/* AprovaAI — Banco expandido Inspetor de Elétrica N1
 * Conteúdo autoral de reforço. Questões oficiais não são reproduzidas.
 * O banco é organizado por tópicos do edital e por situações recorrentes em provas técnicas.
 */
(function(){
const Q=[]; let n=1;
const add=(disc,assunto,sub,en,alts,g,exp,prova)=>Q.push({id:'IEE-'+String(n++).padStart(3,'0'),disciplina:disc,assunto,subassunto:sub,enunciado:en,alternativas:{A:alts[0],B:alts[1],C:alts[2],D:alts[3],E:alts[4]},gabarito:g,explicacao:exp,tipo:'inedita',fonte:'Autorais AprovaAI — reforço por tópicos do edital PROMINP/Cesgranrio',prova});
function calc(d,a,s,exp,alts,g='C',p='Prova 3 - Elétrica N1'){add('Eletrotécnica',d,s,a,alts,g,exp,p)}

/* =========================
   PROVA 1 — MATEMÁTICA
   ========================= */
const pctA=[10,15,20,25,30,12,8,18,35,40];
pctA.forEach((pct,k)=>{const base=100+25*k,val=base*(1+pct/100);add('Matemática','Porcentagem','Acréscimo',`Um valor de ${base} recebe acréscimo de ${pct}%. O novo valor é:`,[`${val-20}`,`${val-10}`,`${val}`,`${val+10}`,`${val+20}`],'C',`Calcula-se ${base}×${pct}/100=${base*pct/100}. Logo, ${base}+${base*pct/100}=${val}.`,'Prova 1 - Básica Geral')});
const pctD=[5,8,10,12,15,20,25,30,35,40];
pctD.forEach((pct,k)=>{const base=200+30*k,val=base*(1-pct/100);add('Matemática','Porcentagem','Desconto',`Um equipamento custa ${base} e sofre desconto de ${pct}%. O preço final é:`,[`${val-10}`,`${val-5}`,`${val}`,`${val+5}`,`${val+10}`],'C',`O desconto é ${base*pct/100}; ${base}-${base*pct/100}=${val}.`,'Prova 1 - Básica Geral')});
[[4,20,7],[5,25,8],[6,42,10],[8,56,12],[10,75,14],[12,84,18],[15,90,20],[7,49,9],[9,72,15],[11,88,22]].forEach(([a,b,c])=>{const r=b/a*c;add('Matemática','Regra de três','Proporcionalidade',`Se ${a} unidades correspondem a ${b}, quantas correspondem a ${c}, mantendo a proporção?`,[`${r/2}`,`${r-5}`,`${r}`,`${r+5}`,`${r*2}`],'C',`A razão é ${b}/${a}=${b/a}; multiplicando por ${c}, obtém-se ${r}.`,'Prova 1 - Básica Geral')});
for(let x=1;x<=10;x++){const y=3*x+2;add('Matemática','Funções','Função afim',`Para f(x)=3x+2, o valor de f(${x}) é:`,[`${y-4}`,`${y-2}`,`${y}`,`${y+2}`,`${y+4}`],'C',`f(${x})=3×${x}+2=${y}.`,'Prova 1 - Básica Geral')}
for(let x=1;x<=10;x++){const y=x*x-4*x+3;add('Matemática','Funções','Função quadrática',`Para f(x)=x²−4x+3, f(${x}) vale:`,[`${y-3}`,`${y-1}`,`${y}`,`${y+1}`,`${y+3}`],'C',`Substituindo x=${x}: ${x}²−4×${x}+3=${y}.`,'Prova 1 - Básica Geral')}
[[0,0,3,4],[1,1,4,5],[0,2,6,10],[2,3,5,9],[4,1,10,5]].forEach(([x1,y1,x2,y2])=>{const d=Math.hypot(x2-x1,y2-y1);const s=d.toFixed(2).replace('.',',');add('Matemática','Geometria analítica','Distância entre pontos',`A distância entre (${x1},${y1}) e (${x2},${y2}) é aproximadamente:`,[`${(d-2).toFixed(2)}`,`${(d-1).toFixed(2)}`,`${d.toFixed(2)}`,`${(d+1).toFixed(2)}`,`${(d+2).toFixed(2)}`].map(v=>v.replace('.',',')),'C',`Aplica-se d=√[(x₂−x₁)²+(y₂−y₁)²]≈${s}.`,'Prova 1 - Básica Geral')});
[[3,4],[5,12],[6,8],[8,15],[9,12],[12,16]].forEach(([op,adj])=>{const hyp=Math.hypot(op,adj);add('Matemática','Trigonometria','Teorema de Pitágoras',`Um triângulo retângulo tem catetos ${op} e ${adj}. A hipotenusa é:`,[`${hyp-2}`,`${hyp-1}`,`${hyp}`,`${hyp+1}`,`${hyp+2}`],'C',`h=√(${op}²+${adj}²)=√${op*op+adj*adj}≈${hyp}.`,'Prova 1 - Básica Geral')});

/* =========================
   PROVA 1 — FÍSICA
   ========================= */
[[2,3],[4,5],[5,6],[8,2],[10,4],[12,3],[15,2],[20,1],[6,7],[9,5]].forEach(([m,a])=>{const F=m*a;add('Física','Leis de Newton','Segunda lei',`Um corpo de massa ${m} kg possui aceleração ${a} m/s². A força resultante é:`,[`${F-5}`,`${F-2}`,`${F}`,`${F+2}`,`${F+5}`].map(x=>`${x} N`),'C',`F=m·a=${m}×${a}=${F} N.`,'Prova 1 - Básica Geral')});
[[10,2],[18,3],[20,4],[30,6],[40,5],[25,2.5],[12,3],[36,4],[45,9],[50,10]].forEach(([s,t])=>{const v=s/t;add('Física','Mecânica','Cinemática',`Um móvel percorre ${s} m em ${t} s. A velocidade média é:`,[`${v/2}`,`${v-2}`,`${v}`,`${v+2}`,`${v*2}`].map(x=>`${x} m/s`),'C',`v=Δs/Δt=${s}/${t}=${v} m/s.`,'Prova 1 - Básica Geral')});
[[2,10,3],[5,10,2],[4,10,5],[3,10,4],[8,10,2],[6,10,3],[10,10,1],[7,10,5],[12,10,2],[15,10,1]].forEach(([m,g,h])=>{const e=m*g*h;add('Física','Energia mecânica','Energia potencial',`Considerando g=${g} m/s², um corpo de ${m} kg está a ${h} m de altura. Sua energia potencial é:`,[`${e-20} J`,`${e-10} J`,`${e} J`,`${e+10} J`,`${e+20} J`],'C',`Ep=mgh=${m}×${g}×${h}=${e} J.`,'Prova 1 - Básica Geral')});
[['inércia','primeira lei de Newton','movimento uniforme ou repouso se a resultante for nula'],['torque','momento de uma força','força multiplicada pelo braço de alavanca perpendicular'],['calor','processo térmico','energia transferida devido a diferença de temperatura'],['pressão','hidrostática','força normal dividida pela área'],['densidade','hidrostática','massa dividida pelo volume'],['indução','eletromagnetismo','variação do fluxo magnético']].forEach(([tema,ass,resp])=>add('Física',ass,tema,`No contexto de ${ass}, qual afirmação está correta?`,[`A grandeza está associada a ${resp}`,`A grandeza independe de qualquer variável física`,`A grandeza só existe em materiais isolantes`,`A grandeza é definida apenas pela temperatura`,`A grandeza não pode ser medida`],'A',`A definição apresentada corresponde ao conceito físico de ${tema}: ${resp}.`,'Prova 1 - Básica Geral'));

/* =========================
   PROVA 2 — QUALIDADE/METROLOGIA/SEGURANÇA
   ========================= */
const q2=[
['Qualidade','Inspeção de qualidade','Critério de aceitação','O critério de aceitação em uma inspeção serve para:',['Definir como o resultado será considerado conforme ou não conforme','Substituir o desenho','Eliminar a medição','Escolher o fornecedor pelo preço','Definir somente o horário'], 'A','O critério estabelece a referência utilizada para julgar o resultado.'],
['Qualidade','Inspeção de qualidade','Não conformidade','Quando uma medição não atende ao requisito especificado, o resultado deve ser tratado como:',['Não conformidade','Conformidade automática','Calibração','Projeto aprovado','Manutenção preventiva'], 'A','Não atendimento a requisito caracteriza não conformidade.'],
['Qualidade','ISO 9001','Rastreabilidade','A rastreabilidade documental de uma inspeção permite:',['Relacionar o resultado ao item, instrumento, requisito e registro aplicáveis','Eliminar os registros','Dispensar identificação','Alterar o resultado posteriormente sem evidência','Substituir ensaio'], 'A','Rastreabilidade permite reconstruir a relação entre objeto, requisito, método e resultado.'],
['Qualidade','Controle de qualidade','Plano de inspeção','Um plano de inspeção deve indicar:',['Itens, critérios, métodos e registros previstos','Somente o nome do inspetor','Somente o preço do material','Somente o local da obra','Somente a data'], 'A','O plano organiza o que será verificado, como e contra qual critério.'],
['Qualidade','Ação corretiva','Causa raiz','A análise de causa de uma não conformidade procura:',['Identificar a causa que permite prevenir recorrência','Somente encontrar o responsável','Eliminar os registros','Aumentar o estoque','Trocar qualquer componente'], 'A','O objetivo é tratar a causa e evitar repetição do problema.'],
['Metrologia','SI','Tensão','A unidade SI da tensão elétrica é:',['Volt','Ampere','Ohm','Watt','Joule'], 'A','O volt (V) é a unidade SI de tensão elétrica.'],
['Metrologia','SI','Resistência','A unidade SI da resistência elétrica é:',['Volt','Ampere','Ohm','Watt','Joule'], 'C','O ohm (Ω) é a unidade de resistência elétrica.'],
['Metrologia','Conversão de unidades','Comprimento','0,75 m correspondem a:',['7,5 cm','75 cm','750 cm','0,75 cm','7500 cm'], 'B','0,75×100=75 cm.'],
['Metrologia','Conversão de unidades','Tempo','3,5 minutos correspondem a:',['35 s','120 s','180 s','210 s','350 s'], 'D','3,5×60=210 s.'],
['Metrologia','Algarismos significativos','Resultado','O número 0,00520 possui quantos algarismos significativos?',['2','3','4','5','6'], 'B','Os zeros à esquerda não contam; 5, 2 e o zero final contam: 3.'],
['Metrologia','Arredondamento','Casas decimais','Arredondando 8,376 para duas casas decimais, obtém-se:',['8,30','8,36','8,37','8,38','8,40'], 'D','O terceiro decimal é 6; 8,376 arredonda para 8,38.'],
['Metrologia','Calibração','Rastreabilidade','Uma calibração rastreável deve possuir:',['Cadeia documentada até padrões de referência apropriados','Somente uma etiqueta','Apenas inspeção visual','Nenhum registro','Somente a marca do instrumento'], 'A','Rastreabilidade metrológica requer relação documentada com padrões.'],
['Segurança','Segurança e higiene','EPI','EPI é utilizado para:',['Proteção individual contra riscos ocupacionais específicos','Substituir todas as medidas coletivas','Escolher o instrumento de medição','Aumentar a tensão','Eliminar procedimentos'], 'A','EPI é uma barreira de proteção individual; não substitui as demais medidas requeridas.'],
['Segurança','Segurança e higiene','EPC','Um exemplo de proteção coletiva é:',['Barreira/sinalização de isolamento da área de risco','Caneta do inspetor','Multímetro pessoal','Crachá','Bloco de notas'], 'A','Proteções coletivas atuam sobre o ambiente e o grupo exposto.'],
['Segurança','NR-10','Planejamento','Em uma atividade elétrica, procedimentos e análise de riscos devem ser considerados para:',['Controlar perigos e definir medidas preventivas antes da execução','Aumentar a velocidade a qualquer custo','Dispensar isolamento','Eliminar documentação','Substituir treinamento'], 'A','O planejamento seguro antecipa perigos e define controles.']
];
for(const z of q2)add(...z,'Prova 2 - Específica Geral');

/* =========================
   PROVA 3 — ELÉTRICA N1
   ========================= */
[[10,100],[20,120],[5,110],[25,200],[40,160],[8,96],[12,144],[30,90],[15,180],[50,250],[16,128],[24,192]].forEach(([R,V])=>{const I=V/R;add('Eletrotécnica','Lei de Ohm','Corrente',`Uma carga resistiva de ${R} Ω é alimentada por ${V} V. A corrente vale:`,[`${I/2} A`,`${I*0.8} A`,`${I} A`,`${I*1.5} A`,`${I*2} A`],'C',`I=V/R=${V}/${R}=${I} A.`,'Prova 3 - Elétrica N1')});
[[10,2],[5,4],[20,3],[8,5],[15,2],[12,4],[25,2],[6,3],[30,2],[4,5]].forEach(([R,I])=>{const P=R*I*I;add('Eletrotécnica','Potência elétrica','Efeito Joule',`Um resistor de ${R} Ω conduz ${I} A. A potência dissipada é:`,[`${P/2} W`,`${P-10} W`,`${P} W`,`${P+10} W`,`${P*2} W`],'C',`P=R·I²=${R}×${I}²=${P} W.`,'Prova 3 - Elétrica N1')});
[[10,20],[5,15],[12,18],[4,8],[20,30],[6,9],[25,5],[7,14],[8,12],[15,10]].forEach(([r1,r2])=>{const e=r1+r2;add('Eletrotécnica','Associação de resistores','Série',`Dois resistores de ${r1} Ω e ${r2} Ω estão em série. A resistência equivalente é:`,[`${e/2} Ω`,`${e-5} Ω`,`${e} Ω`,`${e+5} Ω`,`${r1*r2} Ω`],'C',`Em série, Req=R1+R2=${e} Ω.`,'Prova 3 - Elétrica N1')});
[[10,20],[5,15],[12,18],[4,8],[20,30],[6,9],[25,5],[7,14],[8,12],[15,10]].forEach(([r1,r2])=>{const e=r1*r2/(r1+r2);add('Eletrotécnica','Associação de resistores','Paralelo',`Dois resistores de ${r1} Ω e ${r2} Ω estão em paralelo. A resistência equivalente é aproximadamente:`,[`${(e/2).toFixed(2)} Ω`,`${e.toFixed(2)} Ω`,`${(e*1.5).toFixed(2)} Ω`,`${r1+r2} Ω`,`${r1*r2} Ω`],'B',`Req=R1R2/(R1+R2)≈${e.toFixed(2)} Ω.`,'Prova 3 - Elétrica N1')});
[100,150,220,311,440].forEach(v=>{const rms=v/Math.sqrt(2);add('Eletrotécnica','Corrente alternada','Valor eficaz',`Para uma tensão senoidal de pico ${v} V, o valor eficaz é aproximadamente:`,[`${(rms/2).toFixed(1)} V`,`${(rms-20).toFixed(1)} V`,`${rms.toFixed(1)} V`,`${(rms+20).toFixed(1)} V`,`${(v*2).toFixed(1)} V`],'C',`Para senoide, Vrms=Vp/√2≈${rms.toFixed(1)} V.`,'Prova 3 - Elétrica N1')});
[50,60,100].forEach(f=>add('Eletrotécnica','Corrente alternada','Frequência',`Uma fonte de ${f} Hz completa quantos ciclos por segundo?`,['5',`${f/2}`,`${f}`,`${f*2}`,`${f*10}`], 'C','Hertz representa ciclos por segundo.','Prova 3 - Elétrica N1'));
[['Potência ativa','W','Potência elétrica'],['Potência reativa','var','Potência elétrica'],['Potência aparente','VA','Potência elétrica']].forEach(([nome,un,ass])=>add('Eletrotécnica',ass,nome,`A unidade de ${nome.toLowerCase()} em CA é:`,['W','VA','var','J','Hz'].map(x=>x),({W:'A',var:'C',VA:'B'})[un],`${nome} é expressa em ${un}.`,'Prova 3 - Elétrica N1'));
[['XL=2πfL','Reatância indutiva','Aumenta quando a frequência aumenta'],['XC=1/(2πfC)','Reatância capacitiva','Diminui quando a frequência aumenta'],['VL=√3·VF','Sistema trifásico','Relaciona tensão de linha e fase em estrela equilibrada']].forEach(([form,ass,resp])=>add('Eletrotécnica',ass,'Relação fundamental',`Qual afirmação é correta para ${form}?`,[resp,'Independe totalmente da frequência','É sempre zero','É definida apenas pela massa','Não possui unidade'], 'A',`${form} é a relação fundamental apresentada; ${resp}.`,'Prova 3 - Elétrica N1'));
[['Transformador','Transferência por indução eletromagnética'],['Motor de indução','Rotor normalmente opera abaixo da velocidade síncrona'],['Inversor de frequência','Controle de frequência/tensão para acionamento do motor'],['Soft starter','Redução dos esforços/corrente de partida'],['Disjuntor termomagnético','Proteção típica contra sobrecarga e curto-circuito'],['DR','Detecção de corrente residual/desequilíbrio'],['Contator','Manobra de circuito de potência por comando elétrico'],['Relé de sobrecarga','Proteção do motor contra sobrecarga conforme ajuste']].forEach(([equip,resp])=>add('Máquinas e dispositivos BT',equip,'Função',`Sobre ${equip}, qual afirmação é correta?`,[resp,'Serve apenas para medir resistência de terra','Elimina todo aterramento','Não possui função de proteção ou controle','É usado somente em circuitos mecânicos'],'A',`A função principal indicada é: ${resp}.`,'Prova 3 - Elétrica N1'));
[['Tensão','paralelo','A tensão é medida em paralelo com os pontos de interesse.'],['Corrente','série','A corrente do ramo deve atravessar o instrumento.'],['Resistência','desenergizado','A resistência deve ser medida em circuito apropriadamente desenergizado e isolado.'],['Isolação','megômetro','O megômetro é empregado para ensaio de resistência de isolamento.'],['Aterramento','ensaio de terra','O ensaio avalia o comportamento/resistência do sistema de aterramento.'],['Sequência de fases','sequencímetro','O instrumento identifica a ordem das fases.']].forEach(([gr,met,resp])=>add('Medições elétricas',gr,'Método',`Para a grandeza ${gr}, qual alternativa descreve corretamente o método/instrumento?`,[resp,'Usa sempre um amperímetro em série','É medido apenas por inspeção visual','Dispensa procedimento','Não pode ser registrado'],'A',resp,'Prova 3 - Elétrica N1'));
[['Unifilar','Representação simplificada dos condutores por simbologia'],['Multifilar','Representação individual dos condutores'],['As built','Configuração efetivamente executada'],['Diagrama de comando','Lógica de acionamento, intertravamento e sinalização'],['Legenda','Identificação/explicação de símbolos e referências']].forEach(([tipo,resp])=>add('Desenho técnico',tipo,'Interpretação',`Em documentação elétrica, qual afirmação sobre ${tipo} é correta?`,[resp,'É apenas um documento financeiro','Não possui simbologia','Substitui todos os registros de inspeção','Serve somente para pintura'],'A',resp,'Prova 3 - Elétrica N1'));

/* Situações de inspeção para aproximar o banco da rotina profissional descrita nas referências. */
const situ=[
['Recebimento','Conferência','Ao receber um equipamento elétrico, uma ação adequada do inspetor é:',['Conferir identificação, especificação, integridade e documentação aplicável','Instalar imediatamente sem inspeção','Descartar a documentação','Alterar a placa do fabricante','Ignorar danos aparentes'],'A','O recebimento deve verificar identidade, requisitos e integridade antes da liberação.'],
['Inspeção','Terminações','Em uma inspeção de terminação elétrica, o inspetor deve observar:',['Fixação, identificação, condição dos terminais e conformidade com o projeto/procedimento','Somente a cor do painel','Somente o peso do cabo','Somente a temperatura ambiente','Somente o fabricante'],'A','A inspeção deve verificar os requisitos físicos e documentais aplicáveis à terminação.'],
['Ensaios','Registro','Após realizar uma medição de isolamento, é importante registrar:',['Instrumento, identificação do item, condição do ensaio e resultado','Somente o nome do inspetor','Somente a hora de saída','Somente o preço do equipamento','Nenhum dado'],'A','O registro deve permitir rastrear o ensaio e seu resultado.'],
['Não conformidade','Tratamento','Quando uma não conformidade elétrica é encontrada, o inspetor deve:',['Registrar o desvio e seguir o fluxo/procedimento de tratamento aplicável','Ocultar o resultado','Corrigir o projeto sem autorização','Apagar a medição','Liberar automaticamente o item'],'A','A não conformidade deve ser documentada e tratada segundo o procedimento.'],
['Preservação','Equipamento','Durante a preservação de equipamento elétrico, deve-se considerar:',['Condições ambientais e orientações do fabricante/procedimento','Somente a cor da embalagem','Somente o peso do equipamento','Somente o custo','Nenhum fator ambiental'],'A','Preservação adequada considera ambiente, proteção e requisitos documentados.'],
['Liberação','Critérios','Um equipamento deve ser liberado para a próxima etapa quando:',['Os requisitos de inspeção aplicáveis estiverem atendidos ou formalmente tratados','Houver qualquer documentação','O equipamento estiver apenas montado','O inspetor não tiver tempo','O material for caro'],'A','A liberação depende dos critérios definidos e do tratamento dos desvios.']
];
for(let j=0;j<4;j++)for(const z of situ)add('Inspeção elétrica',z[0],z[1],z[2],z[3],z[4],z[5],'Prova 2 - Específica Geral');

window.INSPETOR_ELETRICA_EXPANDIDO_BANK=Q;
})();