/* AprovaAI — Banco geral do Inspetor de Elétrica N1
 * Questões autorais, estruturadas a partir do conteúdo programático público do PROMINP/Cesgranrio.
 * Não reproduz questões oficiais.
 */
(function(){
const Q=[];
function add(id,disciplina,assunto,subassunto,enunciado,alts,gabarito,explicacao,prova='Prova 1 - Básica Geral'){
 Q.push({id,disciplina,assunto,subassunto,enunciado,alternativas:{A:alts[0],B:alts[1],C:alts[2],D:alts[3],E:alts[4]},gabarito,explicacao,tipo:'inedita',fonte:'Autorais AprovaAI — conteúdo do Edital PROMINP/Cesgranrio',prova});
}
let n=1;const q=(d,a,s,e,o,g,x,p)=>add('IEG-'+String(n++).padStart(3,'0'),d,a,s,e,o,g,x,p);
// PROVA 1 — PORTUGUÊS
q('Português','Compreensão de texto','Ideia principal','Em um texto técnico, a ideia principal corresponde:', ['Ao assunto central desenvolvido pelo autor','À primeira palavra do texto','A qualquer exemplo isolado','Somente ao título','À última frase necessariamente'],'A','A ideia principal sintetiza o núcleo de sentido desenvolvido no texto.');
q('Português','Compreensão de texto','Inferência','Uma inferência adequada a partir de um texto deve:', ['Decorrer logicamente de informações presentes no texto','Contradizer o texto','Depender apenas de opinião pessoal','Ignorar os dados apresentados','Ser sempre uma informação explícita'],'A','Inferências válidas são conclusões sustentadas pelas informações disponíveis.');
q('Português','Significação de palavras','Contexto','O sentido de uma palavra em um texto deve ser determinado principalmente:', ['Pelo contexto em que foi empregada','Pelo significado de dicionário apenas','Pela posição na página','Pelo tamanho da palavra','Pela quantidade de sílabas'],'A','O contexto pode alterar ou especificar o sentido de um vocábulo.');
q('Português','Significação de palavras','Sinonímia','Em contexto, palavras sinônimas são aquelas que apresentam:', ['Sentidos iguais ou muito próximos no contexto','Sentidos sempre opostos','A mesma quantidade de letras','A mesma origem obrigatoriamente','A mesma classe gramatical necessariamente'],'A','Sinonímia envolve proximidade de sentido, observada no contexto.');
q('Português','Significação de palavras','Antonímia','A relação de antonímia ocorre entre palavras de:', ['Sentidos opostos','Sons idênticos','Grafias idênticas','Mesma pronúncia obrigatoriamente','Mesmo número de letras'],'A','Antônimos apresentam sentidos contrários em determinado contexto.');
q('Português','Coesão','Referência pronominal','Na frase “O inspetor conferiu o equipamento e registrou seu número”, o pronome “seu” estabelece relação com:', ['O inspetor ou o equipamento, conforme o contexto','Somente a palavra “registrou”','A palavra “número”','Uma palavra inexistente','A pontuação'],'A','A referência pronominal é determinada pela estrutura e pelo contexto da oração.');
q('Português','Coesão','Conectivos','O conectivo “portanto” introduz, normalmente, uma ideia de:', ['Conclusão','Causa','Oposição','Condição','Comparação'],'A','“Portanto” é empregado para introduzir conclusão ou consequência lógica.');
q('Português','Coesão','Conectivos','O conectivo “porém” expressa relação de:', ['Oposição','Causa','Conclusão','Finalidade','Explicação'],'A','“Porém” introduz uma ideia contrastante ou adversativa.');
q('Português','Interpretação','Informação explícita','Uma informação explícita em um texto é aquela que:', ['Está diretamente apresentada','Só pode ser deduzida','Contradiz o autor','Depende de fonte externa','É sempre subjetiva'],'A','Informação explícita aparece de forma direta no texto.');
q('Português','Interpretação','Informação implícita','Uma informação implícita é aquela que:', ['Pode ser obtida por dedução a partir do texto','Aparece obrigatoriamente no título','Não possui relação com o texto','É uma opinião do leitor sem base','É sempre falsa'],'A','O implícito é alcançado por leitura inferencial apoiada no conteúdo.');
q('Português','Vocabulário','Sentido literal','O sentido literal de uma expressão corresponde ao:', ['Sentido básico e direto das palavras no contexto','Sentido sempre figurado','Sentido contrário ao dicionário','Sentido produzido somente por ironia','Sentido sem relação com o texto'],'A','Sentido literal é o sentido direto, sem depender de figuração.');
q('Português','Vocabulário','Sentido contextual','O sentido contextual de um termo é aquele:', ['Construído pela relação do termo com o restante do texto','Que independe do texto','Que é sempre o primeiro significado do dicionário','Que não pode variar','Que depende somente da pronúncia'],'A','O contexto orienta o sentido específico assumido pelo vocábulo.');
q('Português','Interpretação','Finalidade','A finalidade de um texto técnico costuma estar relacionada a:', ['Informar, orientar, descrever ou registrar um procedimento/fato','Produzir somente humor','Usar linguagem sem objetivo','Evitar informações verificáveis','Substituir qualquer norma técnica'],'A','Textos técnicos têm finalidade funcional, informativa, instrutiva ou documental.');
q('Português','Interpretação','Coerência','Um texto é coerente quando:', ['Suas ideias mantêm relação lógica e sentido global','Todas as frases têm o mesmo tamanho','Não possui verbos','Usa somente termos técnicos','Não apresenta conectivos'],'A','Coerência diz respeito à organização lógica e ao sentido global do texto.');
q('Português','Interpretação','Tema','Tema e ideia principal se relacionam porque:', ['A ideia principal desenvolve o núcleo temático do texto','São sempre termos opostos','O tema é sempre uma frase completa','A ideia principal não depende do tema','Tema existe apenas em títulos'],'A','O tema delimita o assunto central e a ideia principal expressa o núcleo desenvolvido sobre ele.');
// PROVA 1 — MATEMÁTICA
q('Matemática','Conjuntos','Operações','Se A={1,2,3} e B={3,4}, então A∪B é:', ['{1,2,3,4}','{3}','{1,2}','{4}','{1,2,3}'],'A','A união reúne todos os elementos sem repetição.');
q('Matemática','Conjuntos','Interseção','Se A={1,2,3} e B={3,4}, então A∩B é:', ['{3}','{1,2,3,4}','{1,2}','{4}','∅'],'A','A interseção contém os elementos comuns aos dois conjuntos.');
q('Matemática','Proporcionalidade','Razão','A razão entre 20 e 5 é:', ['4','5','10','15','25'],'A','20/5=4.');
q('Matemática','Regra de três','Proporção','Se 4 peças custam R$ 80, mantendo o mesmo preço unitário, 7 peças custam:', ['R$ 100','R$ 120','R$ 140','R$ 160','R$ 180'],'C','Cada peça custa R$20; 7×20=R$140.');
q('Matemática','Porcentagem','Acréscimo','Um valor de 200 acrescido de 10% passa a ser:', ['210','215','220','230','240'],'C','10% de 200 é 20; 200+20=220.');
q('Matemática','Porcentagem','Desconto','Um equipamento de R$ 500 com desconto de 20% passa a custar:', ['R$ 350','R$ 380','R$ 400','R$ 420','R$ 450'],'C','20% de 500 é 100; 500−100=400.');
q('Matemática','Médias','Média aritmética','A média de 10, 20 e 30 é:', ['15','20','25','30','60'],'B','(10+20+30)/3=20.');
q('Matemática','Funções','Função afim','Na função f(x)=2x+3, f(4) é:', ['7','8','9','10','11'],'C','f(4)=2·4+3=11.');
q('Matemática','Funções','Função quadrática','Para f(x)=x²−4x, o valor de f(2) é:', ['−8','−4','0','4','8'],'C','4−8=−4.');
q('Matemática','Sistemas lineares','Equações','No sistema x+y=10 e x−y=2, o valor de x é:', ['2','4','5','6','8'],'D','Somando as equações: 2x=12, logo x=6.');
q('Matemática','Trigonometria','Seno','Em um triângulo retângulo, sen(θ) é definido como:', ['Cateto oposto/hipotenusa','Cateto adjacente/hipotenusa','Hipotenusa/cateto oposto','Cateto oposto/cateto adjacente','Hipotenusa/cateto adjacente'],'A','Seno é a razão entre o cateto oposto e a hipotenusa.');
q('Matemática','Trigonometria','Cosseno','Em um triângulo retângulo, cos(θ) é definido como:', ['Cateto adjacente/hipotenusa','Cateto oposto/hipotenusa','Hipotenusa/cateto adjacente','Cateto oposto/cateto adjacente','1/seno'],'A','Cosseno é a razão entre o cateto adjacente e a hipotenusa.');
q('Matemática','Geometria plana','Área','A área de um retângulo de 8 m por 3 m é:', ['11 m²','16 m²','24 m²','48 m²','64 m²'],'C','Área=base×altura=8×3=24 m².');
q('Matemática','Geometria espacial','Volume','O volume de um cubo de aresta 2 m é:', ['4 m³','6 m³','8 m³','12 m³','16 m³'],'C','V=a³=2³=8 m³.');
q('Matemática','Geometria plana','Circunferência','O comprimento de uma circunferência de raio r é dado por:', ['2πr','πr²','r²/2','π/r','4πr²'],'A','O comprimento é C=2πr.');
// PROVA 1 — FÍSICA
q('Física','Leis de Newton','Primeira lei','A primeira lei de Newton está relacionada ao princípio da:', ['Inércia','Ação e reação','Conservação da carga','Indução','Flutuação'],'A','A primeira lei descreve a permanência do estado de movimento quando a força resultante é nula.');
q('Física','Leis de Newton','Segunda lei','A relação fundamental da segunda lei de Newton é:', ['F=m·a','F=m/a','F=a/m','F=m+ a','F=m−a'],'A','A força resultante é o produto da massa pela aceleração.');
q('Física','Leis de Newton','Terceira lei','A terceira lei de Newton afirma que ação e reação:', ['Têm mesma intensidade, mesma linha de ação e sentidos opostos, em corpos distintos','Atuam sempre no mesmo corpo','Têm intensidades diferentes','Existem somente em corpos em repouso','Não dependem da interação'],'A','Ação e reação constituem um par de forças da interação entre corpos distintos.');
q('Física','Energia mecânica','Energia cinética','A energia cinética depende da:', ['Massa e velocidade do corpo','Somente da massa','Somente da altura','Somente da temperatura','Pressão atmosférica'],'A','Ec=mv²/2, portanto depende de massa e velocidade.');
q('Física','Energia mecânica','Energia potencial','Próximo à superfície da Terra, a energia potencial gravitacional é proporcional a:', ['Massa, gravidade e altura','Velocidade apenas','Pressão apenas','Área da superfície','Frequência'],'A','Ep=mgh.');
q('Física','Equilíbrio','Equilíbrio estático','Um corpo em equilíbrio estático possui:', ['Força resultante e momento resultante nulos','Velocidade obrigatoriamente alta','Aceleração constante não nula','Força resultante máxima','Energia cinética máxima'],'A','No equilíbrio estático, resultante de forças e de momentos é nula.');
q('Física','Eletrostática','Carga elétrica','Cargas elétricas de sinais iguais:', ['Se repelem','Se atraem','Não interagem','Tornam-se neutras','Sempre se anulam'],'A','Cargas de mesmo sinal se repelem.');
q('Física','Cargas em movimento','Corrente elétrica','A corrente elétrica representa:', ['Movimento ordenado de cargas elétricas','Somente energia térmica','Movimento de ondas mecânicas','Massa por unidade de volume','Força por unidade de área'],'A','Corrente elétrica é associada ao movimento ordenado de cargas.');
q('Física','Eletromagnetismo','Campo magnético','Uma corrente elétrica em um condutor pode produzir:', ['Campo magnético','Somente campo gravitacional','Ausência de efeitos','Somente radiação térmica','Apenas pressão mecânica'],'A','Correntes elétricas produzem campos magnéticos.');
q('Física','Eletromagnetismo','Indução','A indução eletromagnética está relacionada à:', ['Variação de fluxo magnético','Massa do condutor apenas','Pressão do ar','Temperatura ambiente apenas','Densidade do material sem variação de campo'],'A','A variação do fluxo magnético pode induzir força eletromotriz.');
q('Física','Radiações eletromagnéticas','Ondas','Ondas eletromagnéticas podem se propagar:', ['No vácuo','Somente em sólidos','Somente em líquidos','Somente em gases','Apenas em meios condutores'],'A','Ondas eletromagnéticas não necessitam de meio material e propagam-se no vácuo.');
q('Física','Hidrostática','Pressão','A pressão é definida como:', ['Força normal por unidade de área','Massa por volume','Energia por tempo','Velocidade por tempo','Comprimento por massa'],'A','P=F/A.');
q('Física','Mecânica','Velocidade','Velocidade média é calculada por:', ['Deslocamento dividido pelo intervalo de tempo','Massa dividida pela força','Força dividida pela área','Energia dividida pela massa','Tempo dividido pelo deslocamento'],'A','Vm=Δs/Δt.');
q('Física','Mecânica','Aceleração','A aceleração média é:', ['Variação de velocidade dividida pelo intervalo de tempo','Deslocamento dividido pela massa','Força dividida pela área','Energia dividida pela velocidade','Pressão dividida pelo tempo'],'A','a=Δv/Δt.');
q('Física','Processos térmicos','Temperatura','Temperatura está relacionada ao:', ['Estado térmico de um sistema','Peso do objeto apenas','Volume sempre constante','Número de condutores','Valor de tensão elétrica'],'A','Temperatura caracteriza o estado térmico de um sistema.');
// PROVA 2 — ESPECÍFICA GERAL: QUALIDADE / ISO / METROLOGIA / SI / SEGURANÇA
q('Qualidade','Inspeção de qualidade','Conformidade','Em inspeção, um produto conforme é aquele que:', ['Atende aos requisitos especificados aplicáveis','É sempre o mais barato','Tem a maior dimensão','Foi fabricado sem documentação','Nunca precisou de medição'],'A','Conformidade significa atendimento aos requisitos especificados.','Prova 2 - Específica Geral');
q('Qualidade','Inspeção de qualidade','Não conformidade','Uma não conformidade deve ser:', ['Identificada e tratada conforme procedimento aplicável','Ignorada se o equipamento funcionar','Ocultada no registro','Corrigida sem qualquer evidência','Sempre atribuída ao operador'],'A','Não conformidades devem ser registradas e tratadas de acordo com o sistema de gestão aplicável.','Prova 2 - Específica Geral');
q('Qualidade','Inspeção de qualidade','Registro','Um registro de inspeção tem como objetivo principal:', ['Evidenciar o resultado da atividade realizada','Substituir qualquer procedimento','Eliminar a necessidade de ensaio','Servir apenas para publicidade','Impedir rastreabilidade'],'A','Registros documentam resultados e permitem rastreabilidade.','Prova 2 - Específica Geral');
q('Qualidade','Inspeção de qualidade','Critério de aceitação','Critério de aceitação é:', ['Regra ou requisito usado para decidir se um resultado é aceitável','Uma opinião informal','Uma marca do fabricante','Uma unidade de medida','Um método de pagamento'],'A','O critério permite comparar o resultado com o requisito aplicável.','Prova 2 - Específica Geral');
q('Qualidade','Inspeção de qualidade','Rastreabilidade','Rastreabilidade em inspeção significa:', ['Permitir acompanhar a origem, histórico ou registros relacionados ao item/resultado','Eliminar identificação','Evitar registros','Usar somente instrumentos digitais','Substituir a especificação'],'A','Rastreabilidade permite relacionar item, medição, documento, lote ou histórico.','Prova 2 - Específica Geral');
q('Qualidade','Inspeção de qualidade','Procedimento','Um procedimento documentado serve para:', ['Definir de forma controlada como determinada atividade deve ser executada','Substituir a norma física','Eliminar treinamento','Evitar critérios de aceitação','Dispensar registros'],'A','Procedimentos estabelecem métodos e responsabilidades para executar atividades de forma controlada.','Prova 2 - Específica Geral');
q('Qualidade','Inspeção de qualidade','Evidência objetiva','Evidência objetiva é melhor representada por:', ['Registros, medições, documentos ou observações verificáveis','Opinião sem registro','Comentário informal','Suposição','Experiência não documentada'],'A','Evidência objetiva pode ser verificada e sustenta a conclusão da inspeção.','Prova 2 - Específica Geral');
q('ISO 9001','Sistema da qualidade','Abordagem por processos','A abordagem por processos procura:', ['Gerenciar atividades inter-relacionadas como processos','Eliminar controles','Substituir inspeções por opinião','Dispensar indicadores','Impedir melhoria'],'A','A gestão por processos considera entradas, atividades, saídas e interações.','Prova 2 - Específica Geral');
q('ISO 9001','Sistema da qualidade','Melhoria','A melhoria contínua em um sistema de qualidade busca:', ['Aumentar a capacidade de atender requisitos e melhorar resultados','Eliminar registros','Evitar análise de dados','Impedir ações corretivas','Manter qualquer processo sem mudança'],'A','A melhoria contínua procura aprimorar desempenho e capacidade de atender requisitos.','Prova 2 - Específica Geral');
q('ISO 9001','Sistema da qualidade','Documentação','Documentos controlados devem possuir:', ['Identificação e controle adequados à sua utilização','Apenas impressão física','Sempre assinatura manual de todos','Ausência de revisão','Uso sem identificação'],'A','O controle documental busca assegurar identificação, revisão e disponibilização adequadas.','Prova 2 - Específica Geral');
q('ISO 9001','Sistema da qualidade','Ação corretiva','Ação corretiva está relacionada a:', ['Eliminar a causa de uma não conformidade para evitar sua repetição','Corrigir somente a aparência','Registrar um resultado conforme','Trocar qualquer instrumento sem análise','Aumentar a quantidade de documentos'],'A','A ação corretiva atua sobre a causa para evitar recorrência.','Prova 2 - Específica Geral');
q('ISO 9001','Sistema da qualidade','Indicadores','Um indicador de processo é útil para:', ['Acompanhar desempenho por meio de dados mensuráveis','Substituir todos os procedimentos','Evitar análise crítica','Eliminar metas','Impedir melhoria'],'A','Indicadores transformam dados em informação para acompanhamento e decisão.','Prova 2 - Específica Geral');
q('Metrologia','Sistema Internacional de Unidades','Grandezas','A unidade SI de comprimento é:', ['metro','quilograma','segundo','ampere','kelvin'],'A','A unidade básica de comprimento no SI é o metro.','Prova 2 - Específica Geral');
q('Metrologia','Sistema Internacional de Unidades','Massa','A unidade SI de massa é:', ['quilograma','grama','newton','pascal','watt'],'A','A unidade básica de massa do SI é o quilograma.','Prova 2 - Específica Geral');
q('Metrologia','Sistema Internacional de Unidades','Tempo','A unidade SI de tempo é:', ['segundo','minuto','hora','dia','milissegundo'],'A','A unidade básica de tempo é o segundo.','Prova 2 - Específica Geral');
q('Metrologia','Algarismos significativos','Valor medido','Em uma medição, algarismos significativos são:', ['Os dígitos que expressam a precisão/resolução indicada pelo resultado','Somente zeros à esquerda','Somente a unidade','Apenas números inteiros','Somente o último dígito de qualquer número'],'A','Algarismos significativos representam informação sobre a resolução/precisão do valor reportado.','Prova 2 - Específica Geral');
q('Metrologia','Arredondamento','Regra','Ao arredondar um número decimal, a decisão sobre aumentar ou manter o último algarismo depende:', ['Do algarismo seguinte e da regra de arredondamento adotada','Do nome do instrumento','Da unidade apenas','Do operador apenas','Da cor do visor'],'A','O algarismo seguinte orienta o arredondamento segundo a regra estabelecida.','Prova 2 - Específica Geral');
q('Metrologia','Conversão de unidades','Comprimento','1 metro corresponde a:', ['100 centímetros','10 centímetros','1000 centímetros','0,1 centímetro','10000 centímetros'],'A','1 m=100 cm.','Prova 2 - Específica Geral');
q('Metrologia','Conversão de unidades','Área','1 m² corresponde a:', ['10.000 cm²','100 cm²','1.000 cm²','10 cm²','100.000 cm²'],'A','Como 1 m=100 cm, então 1 m²=100²=10.000 cm².','Prova 2 - Específica Geral');
q('Metrologia','Escala e coordenadas','Escala','Em um desenho na escala 1:10, 1 cm no desenho representa:', ['10 cm na realidade','1 cm na realidade','100 cm na realidade','0,1 cm na realidade','1000 cm na realidade'],'A','Na escala 1:10, cada unidade no desenho representa 10 unidades reais.','Prova 2 - Específica Geral');
q('Metrologia','Escala e coordenadas','Coordenadas','Coordenadas em um desenho técnico servem para:', ['Localizar um ponto segundo um sistema de referência','Medir somente temperatura','Substituir a legenda','Definir potência elétrica','Calcular massa automaticamente'],'A','Coordenadas localizam pontos em relação a referências estabelecidas.','Prova 2 - Específica Geral');
q('Segurança','Segurança e higiene do trabalho','EPI','EPI é:', ['Equipamento de Proteção Individual','Equipamento de Projeto Industrial','Elemento de Potência Interna','Ensaio de Proteção de Instalação','Escala de Proteção de Instrumentos'],'A','EPI significa Equipamento de Proteção Individual.','Prova 2 - Específica Geral');
q('Segurança','Segurança e higiene do trabalho','EPC','EPC está relacionado a:', ['Equipamento de Proteção Coletiva','Ensaio de Potência Contínua','Equipamento de Processo de Calibração','Elemento de Proteção de Cabos','Escala de Pressão de Controle'],'A','EPC significa Equipamento de Proteção Coletiva.','Prova 2 - Específica Geral');
q('Segurança','Segurança e higiene do trabalho','Risco elétrico','Antes de realizar uma atividade elétrica, uma medida fundamental é:', ['Identificar perigos e controlar os riscos conforme procedimento aplicável','Começar o serviço imediatamente','Retirar todos os equipamentos de proteção','Ignorar a condição da instalação','Trabalhar sem autorização'],'A','A identificação de perigos e o controle de riscos são etapas fundamentais da segurança.','Prova 2 - Específica Geral');
q('Segurança','Segurança e higiene do trabalho','Sinalização','A sinalização de segurança tem como função:', ['Alertar, orientar ou restringir condutas relacionadas aos riscos','Substituir todos os treinamentos','Eliminar qualquer perigo físico','Registrar medições elétricas','Calibrar instrumentos'],'A','Sinalização comunica perigos, restrições e orientações de segurança.','Prova 2 - Específica Geral');
q('Segurança','Segurança e higiene do trabalho','Higiene','Higiene ocupacional busca principalmente:', ['Reconhecer, avaliar e controlar agentes que possam causar danos à saúde','Aumentar a produção sem critérios','Substituir manutenção','Eliminar inspeções','Calcular resistência elétrica'],'A','Higiene ocupacional trata da identificação e controle de exposições ocupacionais.','Prova 2 - Específica Geral');
window.INSPETOR_ELETRICA_GERAL_BANK=Q;
})();
