// AprovaAI Transpetro 2026 — SAP — questões autorais revisadas
window.TRANSPETRO_EDITAL_2026=[
{id:'SAP26-001',assunto:'ERP / SAP-ERP',subassunto:'Integração',dificuldade:'media',enunciado:'Uma empresa registra uma entrada de mercadoria no SAP e precisa refletir os efeitos relevantes em estoque e contabilidade. Qual característica do ERP explica esse comportamento?',alternativas:{A:'Integração entre processos e módulos',B:'Isolamento de cada área em bancos independentes',C:'Uso exclusivo de arquivos locais',D:'Ausência de regras de negócio',E:'Substituição do controle contábil por planilhas'},gabarito:'A',explicacao:'A integração permite que um evento de negócio produza efeitos coordenados em processos relacionados.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-002',assunto:'FI-AP',subassunto:'Contas a pagar',dificuldade:'facil',enunciado:'No SAP FI, uma obrigação registrada contra um fornecedor é tratada principalmente em qual componente?',alternativas:{A:'FI-AR',B:'FI-AP',C:'CO',D:'FM',E:'HCM'},gabarito:'B',explicacao:'FI-AP significa Accounts Payable e trata de contas a pagar.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-003',assunto:'FI-AR',subassunto:'Contas a receber',dificuldade:'facil',enunciado:'Após uma venda a prazo, a empresa precisa controlar o direito de recebimento do cliente. Esse processo está associado a:',alternativas:{A:'FI-GL',B:'FI-AP',C:'FI-AR',D:'MM',E:'HCM'},gabarito:'C',explicacao:'FI-AR (Accounts Receivable) trata das contas a receber de clientes.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-004',assunto:'FI-GL',subassunto:'Razão geral',dificuldade:'media',enunciado:'Qual finalidade caracteriza melhor o FI-GL?',alternativas:{A:'Administrar exclusivamente fornecedores',B:'Controlar apenas materiais',C:'Gerenciar somente recursos humanos',D:'Registrar e organizar informações do razão geral',E:'Executar somente consultas OLAP'},gabarito:'D',explicacao:'FI-GL (General Ledger) corresponde ao razão geral e concentra registros contábeis conforme a configuração.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-005',assunto:'TRM',subassunto:'Tesouraria e riscos',dificuldade:'media',enunciado:'Uma área financeira precisa administrar liquidez, operações de tesouraria e exposição a riscos financeiros. O escopo corresponde principalmente a:',alternativas:{A:'HCM',B:'MM',C:'TRM',D:'SD',E:'FI-AP'},gabarito:'C',explicacao:'TRM (Treasury and Risk Management) trata de processos de tesouraria e riscos financeiros.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-006',assunto:'FM',subassunto:'Orçamento',dificuldade:'media',enunciado:'No contexto do edital, Funds Management está relacionado principalmente ao:',alternativas:{A:'Controle de recursos orçamentários',B:'Cadastro de clientes',C:'Modelagem BPMN',D:'Gerenciamento de classes UML',E:'Data Mining'},gabarito:'A',explicacao:'FM apoia o controle e acompanhamento de recursos orçamentários.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-007',assunto:'BCS',subassunto:'Consolidação',dificuldade:'media',enunciado:'Uma holding precisa consolidar informações financeiras de várias unidades para produzir uma visão corporativa. Qual capacidade está associada ao BCS?',alternativas:{A:'Gestão de materiais',B:'Consolidação e reporting financeiro',C:'Gestão de pessoal',D:'Contas a pagar exclusivamente',E:'Modelagem de processos'},gabarito:'B',explicacao:'BCS está associado à consolidação e ao reporting financeiro corporativo.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-008',assunto:'CO',subassunto:'Custos e resultados',dificuldade:'media',enunciado:'A controladoria deseja analisar custos internos por objetos de custo e resultados gerenciais. Qual módulo é o mais diretamente relacionado?',alternativas:{A:'SD',B:'HCM',C:'MM',D:'CO',E:'FI-AR'},gabarito:'D',explicacao:'CO (Controlling) apoia o controle e a análise gerencial de custos e resultados.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-009',assunto:'MM',subassunto:'Materiais e compras',dificuldade:'facil',enunciado:'Um processo envolve requisição, compra e movimentação de materiais. Qual módulo SAP está mais diretamente associado?',alternativas:{A:'MM',B:'SD',C:'HCM',D:'TRM',E:'BCS'},gabarito:'A',explicacao:'MM (Materials Management) cobre materiais, compras e suprimentos.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-010',assunto:'SD',subassunto:'Vendas e distribuição',dificuldade:'facil',enunciado:'Pedidos de clientes, expedição e distribuição pertencem principalmente ao escopo de:',alternativas:{A:'CO',B:'SD',C:'FM',D:'HCM',E:'FI-GL'},gabarito:'B',explicacao:'SD (Sales and Distribution) apoia vendas e distribuição.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-011',assunto:'HCM',subassunto:'Capital humano',dificuldade:'facil',enunciado:'Qual módulo está diretamente relacionado a processos de gestão de pessoas e capital humano?',alternativas:{A:'HCM',B:'MM',C:'TRM',D:'SD',E:'FM'},gabarito:'A',explicacao:'HCM (Human Capital Management) cobre processos de recursos humanos e gestão de pessoas.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-012',assunto:'SAP-BI',subassunto:'Informação gerencial',dificuldade:'media',enunciado:'Qual situação representa melhor uma finalidade de SAP-BI?',alternativas:{A:'Criar senha de usuário',B:'Executar somente uma compra',C:'Disponibilizar informações organizadas para análise gerencial',D:'Substituir todos os módulos ERP',E:'Modelar somente diagramas UML'},gabarito:'C',explicacao:'BI organiza e disponibiliza informações para análise e apoio à decisão.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-013',assunto:'Integração SAP',subassunto:'Integração entre módulos',dificuldade:'dificil',enunciado:'Uma empresa quer evitar que o mesmo fato econômico seja digitado separadamente por várias áreas. Qual benefício da integração SAP atende diretamente ao objetivo?',alternativas:{A:'Eliminação de todos os controles',B:'Duplicação obrigatória de dados',C:'Isolamento dos processos',D:'Compartilhamento consistente de dados entre processos',E:'Substituição do ERP por arquivos CSV'},gabarito:'D',explicacao:'A integração permite compartilhar dados entre processos relacionados e reduz redundância.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-014',assunto:'Report Writer',subassunto:'Relatórios',dificuldade:'media',enunciado:'Uma equipe precisa definir um relatório a partir de estruturas e dados configurados no ambiente SAP. Qual ferramenta do edital é diretamente relacionada?',alternativas:{A:'Report Writer',B:'BPMN',C:'MER',D:'Scrum',E:'OLAP'},gabarito:'A',explicacao:'Report Writer é uma ferramenta de definição e geração de relatórios no ambiente SAP.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-015',assunto:'Report Painter',subassunto:'Relatórios',dificuldade:'media',enunciado:'Sobre o Report Painter, assinale a alternativa correta.',alternativas:{A:'É um módulo de recursos humanos',B:'É uma ferramenta para definir e apresentar relatórios',C:'É um algoritmo de classificação',D:'É uma linguagem de programação',E:'É um método de elicitação'},gabarito:'B',explicacao:'Report Painter é utilizado para definição e apresentação de relatórios.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-016',assunto:'Segurança SAP',subassunto:'Menor privilégio',dificuldade:'dificil',enunciado:'Em uma auditoria, um usuário possui autorizações além das necessárias para sua função. Qual princípio deve orientar a correção?',alternativas:{A:'Conceder todas as autorizações',B:'Compartilhar a senha',C:'Aplicar o princípio do menor privilégio',D:'Eliminar auditoria',E:'Usar um perfil único'},gabarito:'C',explicacao:'O menor privilégio restringe as autorizações ao necessário para a função.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-017',assunto:'Consolidação contábil',subassunto:'Visão corporativa',dificuldade:'dificil',enunciado:'Ao consolidar demonstrações de diferentes unidades, busca-se principalmente:',alternativas:{A:'Produzir uma visão financeira corporativa conforme as regras de consolidação',B:'Criar bancos independentes',C:'Listar usuários',D:'Mostrar apenas estoque',E:'Criar um diagrama UML'},gabarito:'A',explicacao:'A consolidação combina informações de diferentes unidades para uma visão corporativa.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-018',assunto:'Fluxo de caixa',subassunto:'Liquidez',dificuldade:'media',enunciado:'Para acompanhar a liquidez, uma análise de fluxo de caixa deve considerar principalmente:',alternativas:{A:'Somente depreciação',B:'Entradas, saídas e disponibilidade financeira',C:'Número de usuários',D:'Quantidade de materiais',E:'Diagramas de processo'},gabarito:'B',explicacao:'Fluxo de caixa acompanha entradas, saídas e disponibilidade financeira ao longo do tempo.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-019',assunto:'FI-AP / FI-AR',subassunto:'Integração financeira',dificuldade:'dificil',enunciado:'Uma venda a prazo é registrada e posteriormente recebida. Qual combinação representa melhor os processos financeiros envolvidos?',alternativas:{A:'FI-AP na venda e HCM no recebimento',B:'FI-AR no registro do direito e FI-AR no recebimento',C:'MM no direito e SD no pagamento',D:'FM em ambos os eventos',E:'TRM substituindo o razão geral'},gabarito:'B',explicacao:'O direito contra o cliente e seu recebimento pertencem ao ciclo de contas a receber.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'},
{id:'SAP26-020',assunto:'MM / FI',subassunto:'Integração',dificuldade:'dificil',enunciado:'Uma entrada de mercadoria pode gerar efeitos em estoque e contabilidade. Esse cenário ilustra principalmente:',alternativas:{A:'Integração entre processos logísticos e financeiros',B:'Isolamento do MM',C:'Substituição do FI pelo HCM',D:'Ausência de documento contábil',E:'Uso exclusivo do BI'},gabarito:'A',explicacao:'A integração ERP permite que processos logísticos produzam reflexos financeiros conforme a configuração.',fonte:'Edital Transpetro 2026 — questão autoral AprovaAI'}
];