// AprovaAI Transpetro 2026 — Português, Inglês e Gestão — questões autorais revisadas
window.TRANSPETRO_EXTRA_DIAS=[
{id:'L26-001',assunto:'Português — coesão',subassunto:'Referência pronominal',dificuldade:'media',enunciado:'Leia: “A empresa revisou o procedimento antes de publicá-lo. Essa medida reduziu dúvidas entre os empregados.” No trecho, “Essa medida” retoma:',alternativas:{A:'a publicação',B:'os empregados',C:'a revisão do procedimento',D:'as dúvidas',E:'o procedimento'},gabarito:'C',explicacao:'“Essa medida” retoma a ação de revisar o procedimento.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-002',assunto:'Português — coesão',subassunto:'Conectivos',dificuldade:'media',enunciado:'“O sistema foi atualizado; entretanto, alguns usuários continuaram relatando falhas.” O conectivo “entretanto” estabelece relação de:',alternativas:{A:'causa',B:'oposição',C:'conclusão',D:'condição',E:'finalidade'},gabarito:'B',explicacao:'“Entretanto” introduz oposição ou contraste.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-003',assunto:'Português — coesão',subassunto:'Retomada',dificuldade:'dificil',enunciado:'Em “O relatório foi revisado pelos analistas. O documento, depois de aprovado, foi encaminhado à diretoria”, “O documento” funciona como:',alternativas:{A:'retomada referencial',B:'antecipação de argumento',C:'coordenação sindética',D:'elipse verbal',E:'regência nominal'},gabarito:'A',explicacao:'“O documento” retoma “O relatório”, estabelecendo coesão referencial.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-004',assunto:'Português — compreensão',subassunto:'Inferência',dificuldade:'media',enunciado:'Um texto afirma que uma equipe reduziu retrabalho após padronizar procedimentos, mas não informa que a padronização tenha eliminado todos os erros. É correto inferir que:',alternativas:{A:'todos os erros foram eliminados',B:'o retrabalho aumentou',C:'a padronização contribuiu para reduzir o retrabalho',D:'os procedimentos deixaram de existir',E:'a equipe passou a trabalhar sem controle'},gabarito:'C',explicacao:'A inferência deve respeitar o limite das informações do texto.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-005',assunto:'Português — semântica',subassunto:'Concessão',dificuldade:'media',enunciado:'Em “O projeto avançou apesar dos obstáculos”, a expressão “apesar dos obstáculos” introduz ideia de:',alternativas:{A:'concessão',B:'causa',C:'finalidade',D:'consequência',E:'proporção'},gabarito:'A',explicacao:'“Apesar de” é uma locução de valor concessivo.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-006',assunto:'Português — sintaxe',subassunto:'Oração substantiva',dificuldade:'dificil',enunciado:'Em “A equipe informou que o serviço seria retomado”, a oração “que o serviço seria retomado” exerce função de:',alternativas:{A:'subordinada substantiva objetiva direta',B:'subordinada adverbial causal',C:'coordenada adversativa',D:'subordinada adjetiva explicativa',E:'coordenada assindética'},gabarito:'A',explicacao:'A oração completa o sentido de “informou” e funciona como objeto direto.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-007',assunto:'Português — pontuação',subassunto:'Oração explicativa',dificuldade:'dificil',enunciado:'Assinale a frase em que as vírgulas isolam uma oração de valor explicativo:',alternativas:{A:'Os analistas revisaram, o relatório.',B:'O sistema, que estava indisponível, voltou a operar.',C:'Quando chegou o técnico, iniciou-se o atendimento.',D:'O gerente solicitou revisão, e aprovou o documento.',E:'O procedimento foi revisado pelos analistas, ontem.'},gabarito:'B',explicacao:'A oração “que estava indisponível” tem valor explicativo e é isolada por vírgulas.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-008',assunto:'Português — concordância',subassunto:'Concordância verbal',dificuldade:'media',enunciado:'Assinale a alternativa de acordo com a norma-padrão:',alternativas:{A:'Houveram várias alterações no sistema.',B:'Fazem dois anos que o projeto começou.',C:'Devem existir alternativas para o problema.',D:'Existe muitas soluções possíveis.',E:'Haviam documentos pendentes.'},gabarito:'C',explicacao:'O verbo “existir” concorda com “alternativas”. “Haver” no sentido de existir e “fazer” indicando tempo são impessoais.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-009',assunto:'Português — regência e crase',subassunto:'Crase',dificuldade:'media',enunciado:'Assinale a alternativa em que o emprego da crase está adequado:',alternativas:{A:'O técnico retornou à unidade após o almoço.',B:'O relatório foi entregue à todos.',C:'A equipe começou à revisar o processo.',D:'O sistema atende à usuários externos.',E:'O analista se referiu à um procedimento antigo.'},gabarito:'A',explicacao:'“Retornar a” + “a unidade” resulta em “à unidade”.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-010',assunto:'Português — colocação pronominal',subassunto:'Próclise',dificuldade:'media',enunciado:'Assinale a construção em que a próclise é favorecida por palavra atrativa:',alternativas:{A:'Entregaram-me o relatório.',B:'Não me entregaram o relatório.',C:'Entregar-me-ão o relatório.',D:'Entregaram o relatório-me.',E:'Entregaram-me, não, o relatório.'},gabarito:'B',explicacao:'A palavra negativa “não” favorece a próclise.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-011',assunto:'Inglês — compreensão',subassunto:'Ideia principal',dificuldade:'media',enunciado:'Read: “The company adopted a new maintenance system to reduce downtime and improve planning. After six months, managers reported fewer unplanned interruptions.” The main purpose of the new system was to:',alternativas:{A:'increase interruptions',B:'replace managers',C:'reduce downtime and improve planning',D:'eliminate planning',E:'increase equipment failures'},gabarito:'C',explicacao:'The first sentence explicitly states the purposes of the new system.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-012',assunto:'Inglês — compreensão',subassunto:'Referência',dificuldade:'media',enunciado:'In “The analysts reviewed the reports and updated them before the meeting”, the pronoun “them” refers to:',alternativas:{A:'analysts',B:'reports',C:'meeting',D:'updates',E:'systems'},gabarito:'B',explicacao:'“Them” is a plural object pronoun referring to “the reports”.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-013',assunto:'Inglês — gramática semântica',subassunto:'Modal',dificuldade:'media',enunciado:'In “Employees must follow the safety procedure”, the modal “must” expresses:',alternativas:{A:'possibility',B:'permission',C:'obligation',D:'past ability',E:'past habit'},gabarito:'C',explicacao:'“Must” expresses obligation in this context.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-014',assunto:'Inglês — compreensão',subassunto:'Conectivo',dificuldade:'media',enunciado:'In “The system is expensive; however, it provides reliable information”, “however” indicates:',alternativas:{A:'contrast',B:'cause',C:'purpose',D:'time sequence',E:'condition'},gabarito:'A',explicacao:'“However” introduces contrast.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'L26-015',assunto:'Inglês — gramática semântica',subassunto:'Present perfect',dificuldade:'media',enunciado:'In “The team has completed the migration”, the present perfect primarily indicates:',alternativas:{A:'a completed action with relevance to the present',B:'a future obligation',C:'a prohibition',D:'an action occurring only in the past',E:'a hypothetical condition'},gabarito:'A',explicacao:'The present perfect connects a past action to the present context.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'G26-001',assunto:'PMBOK 7',subassunto:'Princípios',dificuldade:'media',enunciado:'No PMBOK 7, a orientação por princípios e domínios de desempenho busca:',alternativas:{A:'prescrever um único método para todos os projetos',B:'orientar a entrega de valor e o desempenho considerando o contexto',C:'eliminar adaptação',D:'substituir stakeholders por ferramentas',E:'tratar todo projeto como operação contínua'},gabarito:'B',explicacao:'O PMBOK 7 enfatiza princípios, domínios de desempenho, contexto e entrega de valor.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'G26-002',assunto:'PMBOK 7',subassunto:'Stakeholders',dificuldade:'media',enunciado:'Um stakeholder importante passa a resistir após uma mudança de escopo. Qual resposta é mais adequada?',alternativas:{A:'Ignorá-lo',B:'Cancelar a mudança sem análise',C:'Compreender expectativas, impacto e estratégia de engajamento',D:'Removê-lo do projeto',E:'Transferir toda responsabilidade'},gabarito:'C',explicacao:'O engajamento deve considerar expectativas, influência, impacto e estratégia de relacionamento.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'G26-003',assunto:'Scrum',subassunto:'Daily Scrum',dificuldade:'media',enunciado:'Qual evento do Scrum permite aos Developers inspecionar o progresso em direção ao Sprint Goal e adaptar o plano de trabalho?',alternativas:{A:'Sprint Review',B:'Sprint Retrospective',C:'Daily Scrum',D:'Project Charter',E:'Release Planning'},gabarito:'C',explicacao:'O Daily Scrum é voltado à inspeção do progresso em direção ao Sprint Goal e à adaptação do plano.',fonte:'Scrum Guide — questão autoral AprovaAI'},
{id:'G26-004',assunto:'Kanban',subassunto:'WIP',dificuldade:'media',enunciado:'Uma equipe limita o número de itens simultaneamente em execução. O objetivo principal é:',alternativas:{A:'aumentar multitarefa sem limite',B:'controlar WIP e melhorar o fluxo',C:'obrigar Sprints fixas',D:'eliminar políticas explícitas',E:'substituir o backlog por cronograma anual'},gabarito:'B',explicacao:'Limites de WIP ajudam a controlar o trabalho em progresso e melhorar o fluxo.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'G26-005',assunto:'Agile',subassunto:'Manifesto',dificuldade:'facil',enunciado:'Qual alternativa é coerente com os valores do Manifesto Ágil?',alternativas:{A:'Processos e ferramentas acima de indivíduos',B:'Contrato acima da colaboração',C:'Responder a mudanças acima de seguir rigidamente um plano',D:'Documentação acima de software funcionando',E:'Eliminar feedback do cliente'},gabarito:'C',explicacao:'Um dos quatro valores prioriza responder a mudanças em vez de seguir rigidamente um plano.',fonte:'Manifesto for Agile Software Development — questão autoral AprovaAI'}
];
window.TRANSPETRO_EDITAL_2026=(window.TRANSPETRO_EDITAL_2026||[]).concat(window.TRANSPETRO_EXTRA_DIAS);