window.TRANSPETRO_EDITAL_2026=[
{id:'SAP26-041',assunto:'ERP / SAP-ERP',subassunto:'Decisão gerencial',dificuldade:'dificil',enunciado:'Uma organização adota ERP para apoiar decisões com informações integradas e atualizadas. Qual benefício está mais diretamente relacionado?',alternativas:{A:'Disponibilizar dados integrados para análise e decisão',B:'Eliminar processos de negócio',C:'Impedir compartilhamento de dados',D:'Substituir toda contabilidade por planilhas',E:'Eliminar a necessidade de governança'},gabarito:'A',explicacao:'A integração de informações melhora a disponibilidade de dados para análise e decisão.',fonte:'Questão autoral AprovaAI — baseada em incidência CESGRANRIO 2023'},
{id:'SAP26-042',assunto:'ERP / SAP-ERP',subassunto:'Aderência',dificuldade:'dificil',enunciado:'Durante a implantação de um ERP, uma funcionalidade padrão não atende integralmente a um processo crítico. Qual abordagem é tecnicamente mais adequada?',alternativas:{A:'Avaliar processo, parametrização, aderência e custo de eventual customização',B:'Customizar tudo imediatamente',C:'Eliminar o processo',D:'Criar uma planilha paralela obrigatória',E:'Desativar a integração'},gabarito:'A',explicacao:'A decisão deve considerar aderência, parametrização, impacto e custo/risco de customização.',fonte:'Questão autoral AprovaAI — baseada em incidência CESGRANRIO 2023'},
{id:'SAP26-043',assunto:'Banco de Dados / DW',subassunto:'Data Warehouse',dificuldade:'media',enunciado:'Qual descrição melhor caracteriza um Data Warehouse?',alternativas:{A:'Repositório integrado voltado à análise de grandes volumes de dados históricos',B:'Banco exclusivamente transacional para operações do dia a dia',C:'Sistema de autenticação',D:'Arquivo temporário de logs',E:'Tabela usada apenas para cadastro'},gabarito:'A',explicacao:'DW consolida dados históricos de múltiplas fontes para análise.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-044',assunto:'Banco de Dados / DW',subassunto:'Data Mart',dificuldade:'media',enunciado:'Uma área de logística precisa de um repositório analítico específico para suas necessidades. Qual solução é mais compatível?',alternativas:{A:'Data Mart',B:'Servidor SMTP',C:'Sprint Backlog',D:'Tabela de usuários SAP',E:'Gateway BPMN'},gabarito:'A',explicacao:'Data Mart atende necessidades analíticas específicas de uma área ou departamento.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-045',assunto:'OLAP',subassunto:'Operadores',dificuldade:'media',enunciado:'Quais operadores são característicos de ambientes OLAP?',alternativas:{A:'Drill-down e roll-up',B:'Commit e rollback apenas',C:'GET e POST apenas',D:'Compile e link',E:'Fork e merge'},gabarito:'A',explicacao:'Drill-down e roll-up são operações clássicas de análise multidimensional.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-046',assunto:'OLAP',subassunto:'Star x Snowflake',dificuldade:'dificil',enunciado:'Em um Data Warehouse, qual comparação entre star schema e snowflake schema é adequada?',alternativas:{A:'Star tende a desnormalizar dimensões; snowflake tende a normalizá-las',B:'Star não possui tabela fato',C:'Snowflake é sempre OLTP',D:'Ambos são idênticos',E:'Snowflake não utiliza dimensões'},gabarito:'A',explicacao:'O star privilegia simplicidade de consulta; o snowflake normaliza mais as dimensões.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-047',assunto:'Mineração de Dados',subassunto:'Classificação',dificuldade:'media',enunciado:'Um modelo recebe exemplos previamente classificados e deve atribuir uma classe a novos registros. A tarefa é:',alternativas:{A:'Classificação',B:'Agrupamento',C:'Pivotagem',D:'ETL',E:'Normalização'},gabarito:'A',explicacao:'Classificação utiliza classes conhecidas para prever a classe de novos registros.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-048',assunto:'Mineração de Dados',subassunto:'Árvore de decisão',dificuldade:'media',enunciado:'Um algoritmo produz uma estrutura hierárquica com condições do tipo SE-ENTÃO para classificação. Qual técnica é essa?',alternativas:{A:'Árvore de decisão',B:'K-means',C:'OLAP',D:'ETL',E:'Star schema'},gabarito:'A',explicacao:'Árvores de decisão organizam condições em nós e ramificações.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-049',assunto:'Mineração de Dados',subassunto:'Associação',dificuldade:'dificil',enunciado:'Uma análise procura conjuntos frequentes de itens e regras do tipo "quem compra X tende a comprar Y". Qual família de técnica é adequada?',alternativas:{A:'Regras de associação',B:'Classificação supervisionada',C:'Drill-down',D:'Modelagem UML',E:'ETL'},gabarito:'A',explicacao:'Regras de associação descobrem relações de coocorrência entre itens.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-050',assunto:'Engenharia de Software',subassunto:'RUP',dificuldade:'dificil',enunciado:'No Processo Unificado, a fase voltada a consolidar a arquitetura e reduzir os principais riscos é:',alternativas:{A:'Elaboração',B:'Construção',C:'Transição',D:'Iniciação',E:'Manutenção'},gabarito:'A',explicacao:'Na Elaboração, a arquitetura é estabilizada e os riscos mais importantes são tratados.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-051',assunto:'Engenharia de Software',subassunto:'Requisitos',dificuldade:'media',enunciado:'Um requisito que estabelece disponibilidade mínima de 99,9% é classificado principalmente como:',alternativas:{A:'Não funcional',B:'Funcional',C:'Caso de uso',D:'Regra de banco',E:'História de usuário'},gabarito:'A',explicacao:'Disponibilidade é atributo de qualidade e, portanto, requisito não funcional.',fonte:'Questão autoral AprovaAI — tema recorrente CESGRANRIO'},
{id:'SAP26-052',assunto:'Engenharia de Software',subassunto:'UML',dificuldade:'media',enunciado:'Para representar relações estruturais entre classes de um sistema, o diagrama adequado é:',alternativas:{A:'Diagrama de classes',B:'Diagrama de sequência',C:'Diagrama de atividades',D:'Diagrama de estados',E:'Diagrama de implantação'},gabarito:'A',explicacao:'O diagrama de classes representa estrutura e relacionamentos entre classes.',fonte:'Questão autoral AprovaAI — tema recorrente CESGRANRIO'},
{id:'SAP26-053',assunto:'Gestão de Projetos',subassunto:'Stakeholders',dificuldade:'media',enunciado:'Stakeholder de um projeto é:',alternativas:{A:'Parte que pode afetar, ser afetada ou perceber-se afetada pelo projeto',B:'Somente o gerente',C:'Somente o cliente',D:'Somente o patrocinador',E:'Somente a equipe técnica'},gabarito:'A',explicacao:'Stakeholder possui interesse ou influência relevante no projeto.',fonte:'Questão autoral AprovaAI — tema recorrente CESGRANRIO'},
{id:'SAP26-054',assunto:'Gestão de Projetos',subassunto:'Projeto, programa e portfólio',dificuldade:'dificil',enunciado:'Qual relação está correta?',alternativas:{A:'Portfólio agrupa investimentos alinhados à estratégia; programa coordena projetos relacionados',B:'Programa é sempre menor que um projeto',C:'Portfólio é uma fase do projeto',D:'Projeto é uma operação contínua',E:'Programa e portfólio são sinônimos'},gabarito:'A',explicacao:'Portfólio é orientado ao alinhamento estratégico; programas coordenam projetos relacionados para benefícios comuns.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-055',assunto:'BPMN',subassunto:'Fluxo de sequência',dificuldade:'media',enunciado:'Em BPMN, o fluxo de sequência representa:',alternativas:{A:'A ordem de execução entre elementos de fluxo dentro de um processo',B:'Apenas troca de mensagens entre pools',C:'Uma chave estrangeira',D:'Uma dimensão',E:'Uma classe'},gabarito:'A',explicacao:'Sequence Flow representa a ordem do fluxo do processo.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2023'},
{id:'SAP26-056',assunto:'BPMN',subassunto:'Fluxo de mensagem',dificuldade:'media',enunciado:'Em BPMN, a comunicação entre participantes distintos é representada por:',alternativas:{A:'Fluxo de mensagem',B:'Fluxo de sequência exclusivamente',C:'Gateway XOR',D:'Objeto de dados',E:'Lane'},gabarito:'A',explicacao:'Message Flow representa comunicação entre participantes/pools.',fonte:'Questão autoral AprovaAI — edital 2026'},
{id:'SAP26-057',assunto:'Sistemas de Informação',subassunto:'Dados e informação',dificuldade:'facil',enunciado:'Dados organizados e contextualizados para apoiar uma decisão constituem:',alternativas:{A:'Informação',B:'Hardware',C:'Código',D:'Ruído',E:'Transação'},gabarito:'A',explicacao:'Informação resulta do processamento/contextualização de dados.',fonte:'Questão autoral AprovaAI — tema recorrente CESGRANRIO'},
{id:'SAP26-058',assunto:'Business Intelligence',subassunto:'ETL',dificuldade:'media',enunciado:'Qual sequência representa corretamente ETL?',alternativas:{A:'Extract, Transform, Load',B:'Evaluate, Test, Link',C:'Enter, Translate, List',D:'Export, Table, Logic',E:'Execute, Transfer, Log'},gabarito:'A',explicacao:'ETL significa Extract, Transform, Load.',fonte:'Questão autoral AprovaAI — tema cobrado pela CESGRANRIO 2018/2023'},
{id:'SAP26-059',assunto:'Business Intelligence',subassunto:'Metadados',dificuldade:'media',enunciado:'Em um ambiente de BI, metadados são importantes porque:',alternativas:{A:'descrevem estrutura, significado, origem e contexto dos dados',B:'substituem os dados',C:'são sempre senhas',D:'são somente dados financeiros',E:'eliminam a necessidade de ETL'},gabarito:'A',explicacao:'Metadados fornecem contexto sobre os dados e sua estrutura/origem.',fonte:'Questão autoral AprovaAI — edital 2026'},
{id:'SAP26-060',assunto:'BSC',subassunto:'Causa e efeito',dificuldade:'dificil',enunciado:'No Balanced Scorecard, o mapa estratégico é útil principalmente para:',alternativas:{A:'mostrar relações de causa e efeito entre objetivos estratégicos',B:'substituir todos os indicadores',C:'modelar tabelas',D:'criar ordens SAP',E:'definir sprints'},gabarito:'A',explicacao:'O mapa estratégico explicita relações entre objetivos das perspectivas.',fonte:'Questão autoral AprovaAI — edital 2026 e incidência CESGRANRIO'}
];
window.TRANSPETRO_EDITAL_2026=Q;
window.TRANSPETRO_CURADO=(window.TRANSPETRO_CURADO||[]).concat(Q);