// AprovaAI Transpetro 2026 — Sistemas e BI — questões autorais revisadas
window.TRANSPETRO_SISTEMAS_BI=[
{id:'SB26-001',assunto:'Sistemas de Informação',subassunto:'Componentes',dificuldade:'media',enunciado:'Uma organização implantará um sistema para apoiar decisões. Além do software, precisa considerar pessoas, processos, dados e tecnologia. Essa visão corresponde ao conceito de:',alternativas:{A:'sistema de informação',B:'apenas banco de dados',C:'sistema operacional',D:'protocolo de rede',E:'linguagem de programação'},gabarito:'A',explicacao:'Sistemas de informação envolvem recursos tecnológicos e organizacionais para produzir e utilizar informação.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-002',assunto:'Tipos de SI',subassunto:'Níveis organizacionais',dificuldade:'media',enunciado:'Um sistema que registra vendas individualmente e mantém os eventos operacionais da empresa está mais próximo de um:',alternativas:{A:'sistema transacional',B:'sistema especialista exclusivamente',C:'sistema estratégico apenas',D:'modelo de dados conceitual',E:'diagrama de processos'},gabarito:'A',explicacao:'Sistemas transacionais apoiam o registro e processamento das operações rotineiras.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-003',assunto:'Ciclo de vida de SI',subassunto:'Manutenção',dificuldade:'media',enunciado:'Após a implantação de um sistema, surge uma mudança legal que exige alteração de funcionalidades. Essa atividade pertence principalmente à fase de:',alternativas:{A:'modelagem conceitual',B:'manutenção/evolução',C:'elicitação inicial apenas',D:'descarte imediato',E:'codificação sem requisitos'},gabarito:'B',explicacao:'Sistemas continuam sendo corrigidos, adaptados e evoluídos após implantação.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-004',assunto:'Requisitos',subassunto:'Funcional e não funcional',dificuldade:'media',enunciado:'“O sistema deve emitir o relatório mensal em até dois segundos.” Esse requisito combina uma função com uma restrição de:',alternativas:{A:'desempenho',B:'estrutura organizacional',C:'modelagem de dados',D:'segurança física do prédio',E:'regra contábil necessariamente'},gabarito:'A',explicacao:'O limite de tempo de resposta é uma característica de desempenho, típica de requisito não funcional.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-005',assunto:'Elicitação',subassunto:'Técnicas',dificuldade:'media',enunciado:'Um analista entrevista usuários, observa o processo atual e compara documentos para descobrir necessidades que ainda não estão formalizadas. Esse conjunto de atividades caracteriza:',alternativas:{A:'elicitação de requisitos',B:'teste de regressão',C:'deploy',D:'normalização de dados',E:'mineração de dados'},gabarito:'A',explicacao:'Elicitação busca descobrir e compreender necessidades e expectativas dos stakeholders usando técnicas como entrevistas e observação.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-006',assunto:'Engenharia de requisitos',subassunto:'Validação',dificuldade:'dificil',enunciado:'Dois requisitos especificam comportamentos incompatíveis para a mesma situação. O problema identificado é principalmente de:',alternativas:{A:'inconsistência',B:'usabilidade',C:'disponibilidade',D:'compressão',E:'indexação'},gabarito:'A',explicacao:'Requisitos conflitantes apresentam inconsistência e precisam ser analisados e resolvidos.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-007',assunto:'ARIS-EPC',subassunto:'Eventos e funções',dificuldade:'media',enunciado:'Em uma modelagem EPC, a combinação de eventos e funções é usada para representar:',alternativas:{A:'a lógica de execução de processos',B:'somente classes de software',C:'somente tabelas relacionais',D:'endereçamento IP',E:'perfis de autorização SAP'},gabarito:'A',explicacao:'EPC (Event-driven Process Chain) representa processos por eventos e funções conectados pela lógica do fluxo.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-008',assunto:'BPMN 2.0',subassunto:'Gateway exclusivo',dificuldade:'dificil',enunciado:'Um processo verifica se uma solicitação foi aprovada. Se sim, segue para execução; se não, segue para correção. Qual elemento BPMN representa melhor essa decisão?',alternativas:{A:'gateway exclusivo',B:'pool',C:'evento de fim',D:'lane',E:'objeto de dados'},gabarito:'A',explicacao:'O gateway exclusivo direciona o fluxo de acordo com uma condição, escolhendo o caminho aplicável.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-009',assunto:'UML 2.5.1',subassunto:'Casos de uso',dificuldade:'media',enunciado:'Para representar que um usuário externo solicita uma funcionalidade de um sistema, o diagrama UML mais apropriado é o de:',alternativas:{A:'casos de uso',B:'classes',C:'componentes',D:'implantação',E:'estados'},gabarito:'A',explicacao:'Casos de uso representam interações entre atores e funcionalidades do sistema.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-010',assunto:'UML 2.5.1',subassunto:'Sequência',dificuldade:'media',enunciado:'Para mostrar a ordem temporal das mensagens trocadas entre objetos durante uma operação, utiliza-se principalmente o diagrama de:',alternativas:{A:'classes',B:'sequência',C:'componentes',D:'pacotes',E:'implantação'},gabarito:'B',explicacao:'O diagrama de sequência enfatiza a ordem temporal das interações.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-011',assunto:'MER',subassunto:'Modelagem de dados',dificuldade:'facil',enunciado:'Em um modelo entidade-relacionamento, “Fornecedor” representa uma entidade e “CNPJ” pode representar:',alternativas:{A:'um atributo da entidade',B:'um relacionamento obrigatório',C:'um processo BPMN',D:'um evento EPC',E:'um gateway'},gabarito:'A',explicacao:'Atributos descrevem propriedades de entidades; CNPJ pode ser um atributo de Fornecedor.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-012',assunto:'Processo Unificado',subassunto:'Fases',dificuldade:'media',enunciado:'No Processo Unificado, a fase de Elaboração tem como uma de suas finalidades centrais:',alternativas:{A:'estabilizar arquitetura e reduzir riscos relevantes',B:'encerrar imediatamente o produto',C:'eliminar requisitos',D:'proibir iterações',E:'substituir testes por documentação'},gabarito:'A',explicacao:'A Elaboração aprofunda requisitos importantes, trata riscos e estabelece uma arquitetura mais estável.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-013',assunto:'ETL',subassunto:'Transformação',dificuldade:'media',enunciado:'Durante um processo ETL, datas de sistemas diferentes são convertidas para um padrão único antes de serem carregadas no ambiente analítico. Essa etapa é de:',alternativas:{A:'extração',B:'transformação',C:'carga',D:'consulta OLAP',E:'modelagem UML'},gabarito:'B',explicacao:'A padronização/conversão dos dados ocorre na transformação.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-014',assunto:'Data Warehouse',subassunto:'Características',dificuldade:'media',enunciado:'Uma característica típica de um Data Warehouse é ser orientado principalmente a:',alternativas:{A:'análise, com dados integrados e históricos',B:'transações operacionais de curtíssimo prazo apenas',C:'controle de acesso físico',D:'execução de código-fonte',E:'modelagem de processos exclusivamente'},gabarito:'A',explicacao:'DW é voltado ao suporte analítico e costuma reunir dados integrados e históricos.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-015',assunto:'Data Mart',subassunto:'Escopo',dificuldade:'media',enunciado:'Uma área financeira precisa de um ambiente analítico focado em seus indicadores, sem necessariamente consultar todo o universo corporativo. Esse ambiente pode ser um:',alternativas:{A:'Data Mart',B:'sistema operacional',C:'gateway BPMN',D:'perfil SAP',E:'diagrama de classes'},gabarito:'A',explicacao:'Data Mart é orientado a um assunto, área ou domínio específico.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-016',assunto:'OLAP',subassunto:'Drill down',dificuldade:'media',enunciado:'Um gerente analisa vendas por ano e, em seguida, detalha para trimestre e mês. A operação OLAP realizada é:',alternativas:{A:'drill down',B:'drill up',C:'slice',D:'pivotagem apenas',E:'ETL'},gabarito:'A',explicacao:'Drill down navega para níveis mais detalhados de uma hierarquia.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-017',assunto:'OLAP',subassunto:'Slice and Dice',dificuldade:'media',enunciado:'Em uma análise multidimensional, o usuário restringe os dados para uma determinada região e dois produtos, mantendo outras dimensões disponíveis. Essa operação é compatível com:',alternativas:{A:'slice and dice',B:'compilação',C:'normalização física',D:'elicitação',E:'controle de versão'},gabarito:'A',explicacao:'Slice e dice representam recortes e filtros sobre dimensões de um espaço multidimensional.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-018',assunto:'Star Schema',subassunto:'Fato e dimensões',dificuldade:'media',enunciado:'Em um esquema estrela, uma tabela fato de vendas está diretamente relacionada às dimensões Produto, Cliente e Tempo. Essa estrutura é:',alternativas:{A:'star schema',B:'snowflake obrigatório',C:'modelo EPC',D:'modelo de estados',E:'fluxo de mensagem'},gabarito:'A',explicacao:'No star schema, a tabela fato central se relaciona diretamente às tabelas de dimensão.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-019',assunto:'Snowflake Schema',subassunto:'Normalização de dimensões',dificuldade:'media',enunciado:'Uma dimensão geográfica é dividida em tabelas de país, estado e cidade relacionadas entre si. Esse desenho caracteriza:',alternativas:{A:'snowflake schema',B:'star schema puro',C:'OLTP sem dimensão',D:'BPMN',E:'UML'},gabarito:'A',explicacao:'Snowflake normaliza dimensões em estruturas relacionadas, aumentando a decomposição das dimensões.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-020',assunto:'Data Mining',subassunto:'Classificação',dificuldade:'media',enunciado:'Um modelo recebe históricos de clientes já rotulados como “adimplente” ou “inadimplente” e aprende a classificar novos clientes. Trata-se de:',alternativas:{A:'agrupamento não supervisionado',B:'classificação supervisionada',C:'ETL',D:'pivotagem',E:'consolidação contábil'},gabarito:'B',explicacao:'Há classes previamente conhecidas nos dados de treinamento, caracterizando classificação supervisionada.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-021',assunto:'Data Mining',subassunto:'Agrupamento',dificuldade:'media',enunciado:'Uma empresa deseja descobrir grupos naturais de clientes sem fornecer previamente rótulos de segmento. A técnica mais adequada é:',alternativas:{A:'classificação supervisionada',B:'agrupamento',C:'ETL',D:'drill down',E:'BPMN'},gabarito:'B',explicacao:'Agrupamento (clustering) busca grupos por similaridade sem classes predefinidas.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'},
{id:'SB26-022',assunto:'Metadados',subassunto:'Descrição dos dados',dificuldade:'facil',enunciado:'Em um ambiente analítico, informações como nome da coluna, tipo, significado e origem são exemplos de:',alternativas:{A:'metadados',B:'dados transacionais',C:'eventos BPMN',D:'requisitos funcionais',E:'mensagens de rede'},gabarito:'A',explicacao:'Metadados descrevem estrutura, significado, origem e outras características dos dados.',fonte:'Questão autoral AprovaAI — estilo Cesgranrio'}
];
window.TRANSPETRO_EDITAL_2026=(window.TRANSPETRO_EDITAL_2026||[]).concat(window.TRANSPETRO_SISTEMAS_BI);