// AprovaAI — banco autoral de Linguagens 2026
// 150 Português + 150 Inglês. Questões são geradas por matrizes de tópicos,
// com classificação para filtro disciplina/assunto.
(function(){
  const PT=[], EN=[];
  const add=(arr,id,ass,sub,stem,correct,dists,exp)=>arr.push({id,disciplina:arr===PT?"Português":"Inglês",assunto:(arr===PT?"Português / ":"Inglês / ")+ass,subassunto:sub,dificuldade:"media",enunciado:stem,alternativas:{A:correct,B:dists[0],C:dists[1],D:dists[2],E:dists[3]},gabarito:"A",explicacao:exp,fonte:"Questão autoral AprovaAI — matriz de conhecimentos gerais 2026"});
  const ptTopics=[
    ["Interpretação de textos","compreensão",30,(i)=>{const x=[["O relatório informa que a redução de paradas ocorreu após a revisão dos procedimentos e a troca de componentes.","A redução teve mais de uma causa."],["A empresa ampliou o treinamento depois de identificar erros no uso do sistema.","O treinamento foi ampliado como resposta aos erros identificados."],["O projeto terminou no prazo, mas custou mais devido a alterações de escopo.","O prazo foi cumprido, embora o custo tenha superado a estimativa."],["O indicador melhorou, porém a direção recomendou observar os dados por mais um trimestre.","A direção recomendou cautela antes de atribuir definitivamente a melhora a uma causa."],["Os chamados críticos foram tratados primeiro, enquanto os demais ficaram para uma etapa posterior.","A equipe priorizou os chamados segundo sua criticidade."]][i%5]; return [x[0]+" Qual conclusão é compatível com o texto?",x[1]];}],
    ["Sintaxe","funções e orações",20,(i)=>[["Em “A equipe revisou o procedimento”, “o procedimento” exerce a função de","objeto direto"],["Em “Os técnicos permaneceram atentos”, “atentos” exerce a função de","predicativo do sujeito"],["Em “A equipe trabalha com segurança”, “com segurança” é","adjunto adverbial de modo"],["Em “Quando o sistema falhou, a equipe iniciou o procedimento”, a oração iniciada por “Quando” expressa","circunstância temporal"],["Em “É necessário que todos participem”, “que todos participem” é","oração subordinada substantiva subjetiva"]][i%5]],
    ["Coesão e coerência","referenciação e conectores",15,(i)=>[["Em “O sistema foi atualizado. Essa mudança reduziu os erros.”, “Essa mudança” retoma","a atualização do sistema"],["Em “A equipe identificou a falha e, por isso, interrompeu o processo”, “por isso” indica","consequência"],["Em “O procedimento é simples, mas exige atenção”, “mas” introduz","oposição"]][i%3]],
    ["Semântica","sentido contextual",15,(i)=>[["Em “A medida foi decisiva para o resultado”, “decisiva” significa","determinante"],["Em “O relatório aponta um cenário favorável”, “favorável” significa","positivo"],["Em “A equipe evitou uma solução improvisada”, “improvisada” caracteriza algo","feito sem planejamento adequado"]][i%3]],
    ["Pontuação","emprego da vírgula e ponto e vírgula",15,(i)=>[["Assinale a frase corretamente pontuada.","Quando o sistema falhou, a equipe acionou o suporte."],["Assinale a frase corretamente pontuada.","O relatório, após a revisão, foi encaminhado ao gestor."],["A alternativa corretamente pontuada é","A equipe concluiu a análise; o gestor, porém, solicitou nova verificação."]][i%3]],
    ["Classes de palavras","classificação morfológica",10,(i)=>[["Em “A equipe analisou cuidadosamente o relatório”, “cuidadosamente” é","advérbio"],["Em “Os novos procedimentos foram aprovados”, “novos” é","adjetivo"],["Em “Todos participaram da reunião”, “Todos” é","pronome indefinido"]][i%3]],
    ["Pronomes","emprego e colocação",10,(i)=>[["Em “A equipe entregou o relatório ao gerente e este o encaminhou”, “este” retoma","o gerente"],["Em “O procedimento que foi aprovado será aplicado”, “que” é","pronome relativo"],["Assinale a forma adequada.","Entregaram-me o relatório ontem."]][i%3]],
    ["Verbos","tempos e modos",10,(i)=>[["Em “Se o servidor falhar, o serviço será interrompido”, “falhar” está no","futuro do subjuntivo"],["Em “A equipe teria concluído o trabalho”, “teria concluído” expressa","hipótese ou condição no futuro do pretérito"],["Em “Quando a equipe chegou, o sistema já havia sido reiniciado”, “havia sido reiniciado” indica","ação anterior a outra ação passada"]][i%3]],
    ["Concordância","verbal e nominal",10,(i)=>[["Assinale a frase adequada à norma-padrão.","Faz dois anos que o sistema foi implantado."],["Assinale a frase adequada à norma-padrão.","Havia muitos relatórios na mesa."],["A frase adequada é","Os dados foram analisados pela equipe."]][i%3]],
    ["Regência","regência verbal",5,(i)=>[["Assinale a regência adequada.","A equipe assistiu à apresentação."],["A construção adequada é","O gestor informou o problema ao diretor."]][i%2]],
    ["Crase","emprego do acento grave",5,(i)=>[["Assinale o emprego correto da crase.","A equipe retornou à unidade após a reunião."],["O emprego correto é","O relatório foi encaminhado à diretoria."]][i%2]],
    ["Reescrita e estrutura textual","preservação de sentido",5,(i)=>[["A reescrita que preserva o sentido de “A equipe concluiu o relatório após revisar os dados” é","Após revisar os dados, a equipe concluiu o relatório."],["A forma que mantém o sentido de “Embora estivesse cansada, a equipe continuou” é","Apesar de estar cansada, a equipe continuou."]][i%2]]
  ];
  let n=1; ptTopics.forEach(([ass,sub,count,fn])=>{for(let i=0;i<count;i++){const [stem,correct]=fn(i);add(PT,"PT26-"+String(n++).padStart(3,"0"),ass,sub,stem,correct,["A alternativa apresenta uma conclusão não sustentada pelo enunciado.","A alternativa atribui ao trecho uma relação diferente da apresentada.","A alternativa acrescenta informação que não está no enunciado.","A alternativa contraria a estrutura ou o sentido indicado."],"A alternativa correta corresponde ao conceito ou à relação linguística indicada pelo enunciado.");}});
  const ENtopics=[
    ["Main idea","main idea",20,(i)=>[["Read: “The company reduced maintenance delays by integrating planning data with field reports.” What is the main idea?","The company reduced delays by integrating planning data with field reports."],["Read: “The report warns that production growth may increase risk if preventive maintenance is postponed.” What is the main idea?","Postponing preventive maintenance may increase risk while production grows."],["Read: “The team adopted a new workflow after repeated manual-entry errors.” What is the main idea?","A new workflow was adopted in response to repeated manual-entry errors."],["Read: “The project met its deadline, but its cost increased after scope changes.” What is the main idea?","The project met the deadline but exceeded its planned cost."],["Read: “The dashboard combines operational and financial indicators.” What is the main idea?","The dashboard combines operational and financial information."]][i%5]],
    ["Specific information","explicit information",20,(i)=>[["The report states that 12 critical work orders were closed in June. How many were closed?","12"],["The system is available from 06:00 to 22:00 on weekdays. What is its availability window?","From 06:00 to 22:00 on weekdays"],["The project has design, implementation and validation phases. Which comes last?","Validation"],["The report identifies procurement as the main source of delay. What is the source?","Procurement"],["The team reviewed 45 records and found 5 inconsistencies. How many were inconsistent?","5"]][i%5]],
    ["Inference","reading inference",15,(i)=>[["Failures decreased after targeted operator training. What can be inferred?","The training may have contributed to reducing failures."],["A release is postponed until security tests are completed. What does this suggest?","Security validation is considered necessary before release."],["The team uses historical data and current indicators to plan maintenance. What can be inferred?","The team considers both past and current information."],["A project needs extra funding after a scope change. What can be inferred?","Scope changes can affect project cost."],["A report recommends monitoring an indicator before changing the process. What does this imply?","The available evidence is not yet considered sufficient for an immediate change."]][i%5]],
    ["Reference","pronoun reference",15,(i)=>[["In “The team updated the procedure. This reduced errors.” What does “This” refer to?","The procedure update"],["In “The report contains a warning. It should be reviewed carefully.” What does “It” refer to?","The report"],["In “The analysts collected the records and organized them by date.” What does “them” refer to?","The records"],["In “The manager approved the plan because it met the requirements.” What does “it” refer to?","The plan"],["In “The system was tested before it was deployed.” What does “it” refer to?","The system"]][i%5]],
    ["Vocabulary in context","meaning",15,(i)=>[["In “The company reduced maintenance downtime”, “downtime” is closest in meaning to","a period when the system is unavailable"],["In “The manager requested a reliable estimate”, “reliable” is closest in meaning to","trustworthy"],["In “The process was revised to eliminate redundant steps”, “redundant” means","unnecessary or repetitive"],["In “The team detected a critical issue”, “detected” is closest in meaning to","identified"],["In “The solution is feasible within the budget”, “feasible” means","practicable"]][i%5]],
    ["Connectors","logical relations",15,(i)=>[["Choose the connector: “The system was stable; ___, the team continued monitoring it.”","however"],["Choose the connector: “The team completed testing; ___, the release was approved.”","therefore"],["Choose the connector: “The process was delayed ___ a supplier failed to deliver.”","because"],["Choose the connector: “___ the system was expensive, it reduced operating costs.”","Although"],["Choose the connector: “The service will continue ___ the server remains available.”","as long as"]][i%5]],
    ["Pronouns","pronoun forms",10,(i)=>[["Choose the correct pronoun: “The analysts completed the report by ___.”","themselves"],["Choose the correct pronoun: “The manager asked ___ to review the data.”","us"],["Choose the correct possessive: “The company updated ___ policy.”","its"],["Choose the correct form: “This report is ___.”","mine"]][i%4]],
    ["Verb tenses","tense selection",10,(i)=>[["Choose the correct form: “The team ___ the report yesterday.”","completed"],["Choose the correct form: “The engineers ___ the system since Monday.”","have been testing"],["Choose the correct form: “By next Friday, the team ___ the migration.”","will have completed"],["Choose the correct form: “When the manager arrived, the meeting ___.”","had started"]][i%4]],
    ["Modal verbs","modality",10,(i)=>[["Choose the best modal: “Employees ___ wear identification badges inside the facility.”","must"],["Choose the best modal: “The system ___ be unavailable during scheduled maintenance.”","may"],["Choose the best modal: “You ___ back up the database before the upgrade.”","should"],["Choose the best modal: “The analyst ___ access the restricted report without authorization.”","cannot"]][i%4]],
    ["Passive voice","passive construction",10,(i)=>[["Choose the correct passive form: “The team reviewed the report yesterday.”","The report was reviewed by the team yesterday."],["Choose the correct passive form: “They will deploy the system next week.”","The system will be deployed next week."],["Choose the correct passive form: “They have completed the tests.”","The tests have been completed."]][i%3]],
    ["Conditional structures","conditionals",10,(i)=>[["Choose the correct form: “If the server fails, the backup system ___ automatically.”","will start"],["Choose the correct form: “If I were the manager, I ___ the process.”","would review"],["Choose the correct form: “If the team had tested the change, the error ___ avoided.”","could have been"]][i%3]]
  ];
  let m=1; ENtopics.forEach(([ass,sub,count,fn])=>{for(let i=0;i<count;i++){const [stem,correct]=fn(i);add(EN,"EN26-"+String(m++).padStart(3,"0"),ass,sub,stem,correct,["The option contradicts the statement or grammatical context.","The option changes the logical relation required.","The option is grammatically or semantically inappropriate.","The option introduces information not supported by the text."],"The selected answer matches the meaning, reference or grammatical structure required by the item.");}});
  window.TRANSPETRO_EDITAL_2026=(window.TRANSPETRO_EDITAL_2026||[]).concat(PT,EN);
  window.TRANSPETRO_LINGUAGEM_COBERTURA={portugues:PT.length,ingles:EN.length,total:PT.length+EN.length};
})();