// Banco dinâmico de treino Transpetro — 2.000 questões geradas a partir da matriz.
// Não são questões oficiais da Cesgranrio.
(function(){
const T=[
["ERP / SAP","ERP e integração empresarial","Uma organização integra compras, estoque e finanças em uma única plataforma. Qual característica de ERP está mais diretamente presente?","B","Integração de dados e processos entre áreas.","A","Isolamento dos sistemas departamentais.","C","Eliminação dos processos de negócio.","D","Uso obrigatório de planilhas.","E","Separação completa dos dados."],
["SAP","ECC e S/4HANA","Ao comparar plataformas SAP, qual afirmação é adequada?","C","ECC e S/4HANA são plataformas distintas e suas características podem ser cobradas separadamente.","A","São sempre sinônimos.","B","São apenas módulos financeiros.","D","S/4HANA é somente uma interface.","E","ECC é uma linguagem de programação."],
["SAP","Fiori","Uma empresa quer aplicações orientadas a tarefas e papéis, com experiência de usuário simplificada. Qual tecnologia se relaciona diretamente?","A","SAP Fiori.","B","IDoc.","C","RFC.","D","SAPscript.","E","ALE."],
["SAP PM","Ordens","No SAP PM, IW31/IW32/IW33 estão associados principalmente a qual objeto?","A","Ordens.","B","Notificações.","C","Pedidos de compra.","D","Faturas.","E","Clientes."],
["SAP PM","Notificações","No SAP PM, IW21/IW22/IW23 estão associados principalmente a qual objeto?","B","Notificações.","A","Ordens.","C","Materiais.","D","Projetos.","E","Faturas."],
["SAP PM","Equipamento e local de instalação","Em uma estrutura técnica de manutenção, qual distinção é adequada?","D","Equipamento é um objeto técnico individualizável; local de instalação representa uma posição funcional na estrutura.","A","São sempre o mesmo objeto.","B","Local de instalação existe apenas em FI.","C","Equipamento é somente um documento financeiro.","E","Nenhum possui histórico."],
["SAP PM","Confirmações","Qual é a finalidade principal da confirmação de uma operação de manutenção?","E","Registrar a execução e informações relacionadas ao trabalho realizado.","A","Criar um cliente.","B","Excluir o equipamento.","C","Criar uma conta contábil.","D","Alterar a estratégia corporativa."],
["Integração SAP","PM x MM","Uma ordem de manutenção necessita de materiais para sua execução. Qual integração é mais diretamente envolvida?","C","PM x MM.","A","PM x SD.","B","PM x HCM.","D","PM x CRM.","E","PM x Marketing."],
["Integração SAP","PM x CO","Custos de uma ordem de manutenção precisam ser acompanhados pelo controlling. Qual integração é mais diretamente relacionada?","A","PM x CO.","B","PM x SD.","C","PM x HCM.","D","PM x CRM.","E","PM x Marketing."],
["Integração SAP","MM x FI","Uma aquisição de material precisa gerar reflexos no processo financeiro. Qual integração está diretamente relacionada?","E","MM x FI.","A","SD x HCM.","B","PM x SD.","C","CO x HCM.","D","PS x HCM."],
["Processos de Negócio","Procure-to-Pay","Qual sequência representa um processo ponta a ponta típico de suprimentos?","A","Necessidade, compra, recebimento e pagamento.","B","Venda, expedição e cobrança.","C","Recrutamento, seleção e treinamento.","D","Projeto, teste e aposentadoria.","E","Modelagem, deploy e rollback."],
["Processos de Negócio","Order-to-Cash","Qual processo está relacionado ao ciclo desde a venda até o recebimento?","B","Order-to-Cash.","A","Procure-to-Pay.","C","Hire-to-Retire.","D","Plan-to-Produce.","E","Issue-to-Resolution."],
["Engenharia de Software","Cascata","Qual característica é mais marcante no modelo Cascata?","A","Fases sequenciais com forte dependência entre etapas.","B","Ausência de planejamento.","C","Entrega exclusivamente contínua.","D","Backlog obrigatório.","E","Uso exclusivo de protótipos."],
["Engenharia de Software","Agile","Qual princípio é compatível com abordagens ágeis?","D","Responder a mudanças e obter feedback ao longo do desenvolvimento.","A","Impedir mudanças.","B","Eliminar participação do cliente.","C","Evitar entregas incrementais.","E","Substituir requisitos por código sem validação."],
["Scrum","Product Goal","Qual item pertence ao Scrum?","B","Product Goal.","A","Gateway BPMN.","C","Cubo OLAP.","D","Razão contábil.","E","Ordem de manutenção."],
["Scrum","Definition of Done","No Scrum, a Definition of Done serve para:","C","Estabelecer critérios compartilhados para considerar um incremento concluído.","A","Definir o orçamento anual.","B","Criar uma ordem SAP.","D","Modelar um banco relacional.","E","Substituir o Product Backlog."],
["BPMN","Elementos","Qual alternativa contém somente elementos fundamentais de BPMN?","A","Eventos, atividades e gateways.","B","Fatos, dimensões e medidas.","C","Sprint, Increment e Product Goal.","D","Commit, rollback e isolamento.","E","Centro de custo, ordem e razão."],
["BPMN","Gateway","Em BPMN, um gateway é usado principalmente para:","C","Controlar divergências e convergências do fluxo conforme regras do processo.","A","Representar sempre uma pessoa.","B","Armazenar código-fonte.","D","Substituir toda atividade.","E","Representar exclusivamente um banco."],
["Banco de Dados","OLTP x OLAP","Qual comparação é mais adequada entre OLTP e OLAP?","E","OLTP prioriza operações transacionais; OLAP prioriza análise e consultas.","A","São sinônimos.","B","OLAP é exclusivo para impressão.","C","OLTP não permite atualização.","D","Possuem exatamente a mesma finalidade."],
["Banco de Dados","Normalização","Qual é uma finalidade clássica da normalização relacional?","B","Reduzir redundâncias e anomalias de atualização.","A","Aumentar duplicação.","C","Eliminar chaves.","D","Impedir consultas.","E","Transformar todo banco em NoSQL."],
["Gestão de Projetos","Projeto x operação","Qual característica diferencia projeto de operação?","A","Projeto é temporário e busca uma entrega específica; operação é contínua e repetitiva.","B","Projeto é sempre repetitivo.","C","Operação sempre termina.","D","Projeto não possui stakeholders.","E","Operação não possui processos."],
["PMBOK","Domínios de desempenho","Qual conjunto contém domínios de desempenho do PMBOK 7?","C","Stakeholders, equipe, planejamento, entrega e medição.","A","Gateway, lane e pool.","B","Fato, dimensão e cubo.","D","Sprint, backlog e increment.","E","IW31, IW32 e IW33."],
["IA / Machine Learning","Aprendizado supervisionado","Em aprendizado supervisionado, o treinamento normalmente utiliza:","D","Exemplos com rótulos ou saídas conhecidas.","A","Somente dados sem referência.","B","Apenas regras fixas.","C","Nenhum dado histórico.","E","Somente imagens sem classe."],
["IA / Machine Learning","Overfitting","Um modelo tem ótimo desempenho no treinamento e piora muito em dados novos. Qual fenômeno é compatível?","A","Overfitting.","B","Normalização.","C","ETL.","D","OLAP.","E","BPMN."],
["Administração / BSC","Planejamento estratégico","Qual elemento está diretamente relacionado ao planejamento estratégico?","B","Direcionamento de longo prazo, objetivos e posicionamento.","A","Somente tarefas diárias.","C","Somente folha de pagamento.","D","Somente manutenção corretiva.","E","Somente lançamentos contábeis."],
["Administração / BSC","BSC","Qual perspectiva do BSC contempla competências, capacitação e inovação?","E","Aprendizado e crescimento.","A","Financeira.","B","Clientes.","C","Processos internos.","D","Mercado."]
];
const C=['Em uma questão de concurso, ','Em uma empresa de grande porte, ','Durante a implantação de um sistema corporativo, ','Em um ambiente de manutenção industrial, ','Durante uma análise de processos, ','Em um projeto de transformação digital, ','Em uma organização integrada por sistemas corporativos, ','Durante uma auditoria de processos, ','Considerando uma situação operacional, ','Em uma equipe de tecnologia, ','Durante o planejamento de uma solução, ','Em um cenário de gestão empresarial, ','Considerando uma empresa que busca eficiência, ','Durante a avaliação de uma arquitetura de sistemas, ','Em uma atividade de gerenciamento, ','Durante uma reunião de análise, ','Considerando dados de uma organização, ','Em uma situação hipotética de prova, ','Durante a definição de requisitos, ','Em uma iniciativa de melhoria de processos,'];
const out=[];for(let n=0;n<2000;n++){const t=T[n%T.length],v=Math.floor(n/T.length);const [assunto,sub,enunciado,g,cor,a,at,b,bt,c,ct,d,dt,e,et]=t;const alt={A:at,B:bt,C:ct,D:dt,E:et};out.push({id:`TP-GEN-${String(n+1).padStart(4,'0')}`,assunto,subassunto:sub,dificuldade:['fácil','médio','difícil'][n%3],enunciado:C[v%C.length]+`Variação ${v+1}: `+enunciado,alternativas:alt,gabarito:g,explicacao:`A alternativa ${g} está correta: ${cor}`,fonte:'TRANSPETRO_2026_SAP_Matriz_Simulados.md — banco de treino gerado'});}window.TRANSPETRO_EXTRA_QUESTOES=out;})();