/* AprovaAI — expansão do banco do Inspetor de Elétrica N1
   Questões autorais de reforço por assunto. */
(function(){
const Q=[];let n=1;
const add=(d,a,s,e,o,g,x,p)=>Q.push({id:'IEE-'+String(n++).padStart(3,'0'),disciplina:d,assunto:a,subassunto:s,enunciado:e,alternativas:{A:o[0],B:o[1],C:o[2],D:o[3],E:o[4]},gabarito:g,explicacao:x,tipo:'inedita',fonte:'Autorais AprovaAI — tópicos PROMINP/Cesgranrio',prova:p});
const P='Prova 1 - Básica Geral',G='Prova 2 - Específica Geral',E='Prova 3 - Elétrica N1';
/* Matemática: porcentagem, proporção, médias, conjuntos, funções, geometria e trigonometria */
[[80,10],[120,15],[160,25],[200,12],[250,20],[300,30],[360,5],[420,10],[500,18],[640,25]].forEach(([v,p])=>{let r=v*(1+p/100);add('Matemática','Porcentagem','Acréscimo',`Um valor de ${v} recebe acréscimo de ${p}%. O novo valor é:`,[`${r-20}`,`${r-10}`,`${r}`,`${r+10}`,`${r+20}`],'C',`O aumento é ${v*p/100}; portanto, o novo valor é ${r}.`,P)});
[[100,10],[180,20],[240,25],[320,15],[400,30],[450,12],[500,18],[600,20],[750,8],[900,35]].forEach(([v,p])=>{let r=v*(1-p/100);add('Matemática','Porcentagem','Desconto',`Um valor de ${v} sofre desconto de ${p}%. O resultado é:`,[`${r-20}`,`${r-10}`,`${r}`,`${r+10}`,`${r+20}`],'C',`O desconto é ${v*p/100}; ${v}-${v*p/100}=${r}.`,P)});
[[5,30,8],[4,24,9],[6,42,11],[8,56,15],[10,70,12],[12,96,18],[7,63,10],[9,81,14],[15,120,20],[20,140,25]].forEach(([a,b,c])=>{let r=b/a*c;add('Matemática','Regra de três','Proporcionalidade',`Se ${a} itens correspondem a ${b}, pela mesma proporção ${c} itens correspondem a:`,[`${r-10}`,`${r-5}`,`${r}`,`${r+5}`,`${r+10}`],'C',`A razão unitária é ${b/a}; multiplicando por ${c}, obtém-se ${r}.`,P)});
for(let x=1;x<=10;x++){let y=4*x+1;add('Matemática','Funções','Função afim',`Na função f(x)=4x+1, f(${x}) vale:`,[`${y-4}`,`${y-2}`,`${y}`,`${y+2}`,`${y+4}`],'C',`4×${x}+1=${y}.`,P)}
[[3,4],[5,12],[6,8],[8,15],[9,12],[12,5],[7,24],[20,21]].forEach(([a,b])=>{let h=Math.hypot(a,b);add('Matemática','Geometria plana','Triângulo retângulo',`Um triângulo retângulo tem catetos ${a} e ${b}. A hipotenusa é aproximadamente:`,[`${(h-2).toFixed(1)}`,`${(h-1).toFixed(1)}`,`${h.toFixed(1)}`,`${(h+1).toFixed(1)}`,`${(h+2).toFixed(1)}`].map(s=>s.replace('.',',')),'C',`Pelo Teorema de Pitágoras, h=√(${a}²+${b}²)≈${h.toFixed(1)}.`,P)});
[[2,4],[3,5],[4,6],[5,7],[6,8],[7,9],[8,10],[9,11]].forEach(([x1,x2],k)=>{let d=Math.abs(x2-x1);add('Matemática','Conjuntos','Operações',`Considere A={${x1},${x1+1},${x1+2}} e B={${x2},${x2+1},${x2+2}}. Qual é a cardinalidade de A?`,['1','2','3','4','5'],'C','A contém exatamente três elementos distintos.',P)});
/* Física */
[[2,4],[3,5],[4,6],[5,7],[6,8],[8,3],[10,2],[12,4],[15,3],[20,2]].forEach(([m,a])=>{let f=m*a;add('Física','Leis de Newton','Segunda lei',`Um corpo de ${m} kg acelera a ${a} m/s². A força resultante é:`,[`${f-5} N`,`${f-2} N`,`${f} N`,`${f+2} N`,`${f+5} N`],'C',`F=m·a=${m}×${a}=${f} N.`,P)});
[[12,3],[20,5],[24,4],[30,6],[45,5],[50,10],[60,12],[72,8],[80,10],[100,20]].forEach(([s,t])=>{let v=s/t;add('Física','Mecânica','Velocidade média',`Um corpo percorre ${s} m em ${t} s. A velocidade média é:`,[`${v/2} m/s`,`${v-2} m/s`,`${v} m/s`,`${v+2} m/s`,`${v*2} m/s`],'C',`v=Δs/Δt=${s}/${t}=${v} m/s.`,P)});
[[2,10,5],[3,10,4],[4,10,3],[5,10,2],[6,10,5],[8,10,4],[10,10,3],[12,10,2]].forEach(([m,g,h])=>{let e=m*g*h;add('Física','Energia mecânica','Energia potencial',`Com g=${g} m/s², um corpo de ${m} kg está a ${h} m. Sua energia potencial é:`,[`${e-20} J`,`${e-10} J`,`${e} J`,`${e+10} J`,`${e+20} J`],'C',`Ep=mgh=${m}×${g}×${h}=${e} J.`,P)});
[['Eletrostática','Cargas','Cargas de mesmo sinal se repelem.'],['Eletromagnetismo','Indução','Variação do fluxo magnético pode induzir tensão.'],['Hidrostática','Pressão','Pressão é força normal dividida pela área.'],['Mecânica','Aceleração','Aceleração é variação da velocidade por unidade de tempo.'],['Processos térmicos','Calor','Calor é energia transferida devido a diferença de temperatura.']].forEach(([a,s,r])=>add('Física',a,s,`Em ${a}, assinale a afirmação correta:`,[r,'A grandeza independe das variáveis físicas','A grandeza é sempre nula','A grandeza só existe em gases','A grandeza não pode ser medida'],'A',r,P));
/* Qualidade / Metrologia / Segurança */
[['Inspeção','Critério de aceitação','Serve para comparar o resultado com requisito especificado.'],['Inspeção','Recebimento','Verifica identificação, integridade e requisitos antes da liberação.'],['Qualidade','Não conformidade','É o não atendimento de um requisito.'],['Qualidade','Ação corretiva','Busca tratar a causa de uma não conformidade para evitar recorrência.'],['Qualidade','Registro','Fornece evidência documentada do que foi realizado/verificado.'],['ISO 9001','Abordagem de processo','Organiza atividades como processos que transformam entradas em saídas.'],['ISO 9001','Foco no cliente','A organização busca atender requisitos aplicáveis do cliente.']].forEach(([a,s,r])=>add('Qualidade',a,s,`No contexto de ${a}, qual alternativa está correta?`,[r,'Dispensa procedimentos','Substitui toda inspeção','Elimina registros','É apenas uma atividade financeira'],'A',r,G));
[['SI','corrente elétrica','Ampere (A)'],['SI','tensão elétrica','Volt (V)'],['SI','resistência elétrica','Ohm (Ω)'],['SI','potência ativa','Watt (W)'],['SI','energia','Joule (J)'],['Conversão','1 m','100 cm'],['Conversão','1 kg','1000 g'],['Conversão','1 min','60 s'],['Arredondamento','12,346 para duas casas','12,35']].forEach(([a,s,r])=>add('Metrologia',a,s,`Assinale a relação correta: ${s}.`,[r,'10 vezes menor que essa relação','100 vezes maior','Sem relação com a unidade','Depende somente da cor do instrumento'],'A',`A relação apresentada está correta: ${r}.`,G));
[['Segurança','EPI','Proteção individual contra risco ocupacional.'],['Segurança','EPC','Proteção coletiva aplicada à área/grupo exposto.'],['Segurança','Risco elétrico','Deve ser identificado, avaliado e controlado antes da atividade.'],['Segurança','Sinalização','Ajuda a impedir acesso indevido e comunicar perigos.'],['Segurança','Procedimento','Define sequência e controles previstos para a atividade.'],['NR-10','Planejamento','A atividade elétrica deve considerar os requisitos de segurança aplicáveis.']].forEach(([a,s,r])=>add('Segurança',a,s,`Sobre ${s}, qual alternativa está correta?`,[r,'Pode ser ignorado quando há pressa','Substitui treinamento','Elimina qualquer perigo automaticamente','É apenas documentação financeira'],'A',r,G));
/* Eletrotécnica */
[[10,100],[20,120],[5,110],[25,200],[40,160],[8,96],[12,144],[30,90],[15,180],[50,250],[16,128],[24,192],[18,216],[32,160]].forEach(([R,V])=>{let I=V/R;add('Eletrotécnica','Lei de Ohm','Corrente',`Uma resistência de ${R} Ω ligada a ${V} V conduz:`,[`${I/2} A`,`${I*0.8} A`,`${I} A`,`${I*1.5} A`,`${I*2} A`],'C',`I=V/R=${V}/${R}=${I} A.`,E)});
[[10,2],[5,4],[20,3],[8,5],[15,2],[12,4],[25,2],[6,3],[30,2],[4,5],[18,2],[10,5]].forEach(([R,I])=>{let p=R*I*I;add('Eletrotécnica','Potência elétrica','Efeito Joule',`Um resistor de ${R} Ω percorrido por ${I} A dissipa:`,[`${p/2} W`,`${p-10} W`,`${p} W`,`${p+10} W`,`${p*2} W`],'C',`P=R·I²=${R}×${I}²=${p} W.`,E)});
[[10,20],[5,15],[12,18],[4,8],[20,30],[6,9],[25,5],[7,14],[8,12],[15,10],[18,6],[22,11]].forEach(([r1,r2])=>{let e=r1+r2;add('Eletrotécnica','Associação de resistores','Série',`Resistores de ${r1} Ω e ${r2} Ω em série têm Req:`,[`${e/2} Ω`,`${e-5} Ω`,`${e} Ω`,`${e+5} Ω`,`${r1*r2} Ω`],'C',`Em série, Req=R1+R2=${e} Ω.`,E)});
[[10,20],[5,15],[12,18],[4,8],[20,30],[6,9],[25,5],[7,14],[8,12],[15,10],[18,6],[22,11]].forEach(([r1,r2])=>{let e=r1*r2/(r1+r2);add('Eletrotécnica','Associação de resistores','Paralelo',`Resistores de ${r1} Ω e ${r2} Ω em paralelo têm Req≈:`,[`${(e/2).toFixed(2)} Ω`,`${e.toFixed(2)} Ω`,`${(e*1.5).toFixed(2)} Ω`,`${r1+r2} Ω`,`${r1*r2} Ω`],'B',`Req=R1R2/(R1+R2)≈${e.toFixed(2)} Ω.`,E)});
[100,150,220,311,440].forEach(v=>{let r=v/Math.sqrt(2);add('Eletrotécnica','Corrente alternada','Valor eficaz',`Uma senoide com ${v} V de pico possui valor eficaz aproximadamente igual a:`,[`${(r/2).toFixed(1)} V`,`${(r-20).toFixed(1)} V`,`${r.toFixed(1)} V`,`${(r+20).toFixed(1)} V`,`${v} V`],'C',`Vrms=Vp/√2≈${r.toFixed(1)} V.`,E)});
[['Potência ativa','W','A potência ativa é medida em watt.'],['Potência reativa','var','A potência reativa é medida em var.'],['Potência aparente','VA','A potência aparente é medida em VA.'],['Fator de potência','P/S','Para carga senoidal, FP=P/S.'],['Reatância indutiva','2πfL','A reatância indutiva aumenta com f.'],['Reatância capacitiva','1/(2πfC)','A reatância capacitiva diminui com f.']].forEach(([a,s,r])=>add('Eletrotécnica',a,s,`Qual relação é correta para ${a}?`,[r,'É sempre zero','Não depende das grandezas elétricas','É definida pela massa','Não pode ser expressa matematicamente'],'A',r,E));
/* Máquinas, medições e desenho */
[['Transformador','Relação de espiras','Vp/Vs=Np/Ns no modelo ideal.'],['Motor de indução','Escorregamento','Em operação normal, o rotor gira abaixo da síncrona.'],['Motor de indução','Velocidade síncrona','ns=120f/p.'],['Inversor de frequência','Função','Permite controlar frequência/tensão aplicadas ao motor.'],['Soft starter','Partida','Reduz esforços e corrente durante a partida.'],['Contator','Manobra','É usado para manobra elétrica por comando.'],['Disjuntor','Proteção','Protege tipicamente contra sobrecarga e curto-circuito.'],['DR','Proteção diferencial','Detecta corrente residual/desequilíbrio.']].forEach(([a,s,r])=>add('Máquinas e dispositivos BT',a,s,`Sobre ${a}, qual afirmação está correta?`,[r,'Substitui automaticamente o aterramento','Serve apenas para medir tensão','Elimina todos os riscos','É um instrumento mecânico'],'A',r,E));
[['Tensão','paralelo','Tensão é medida em paralelo com os pontos de interesse.'],['Corrente','série','Corrente de um ramo é medida com o instrumento em série.'],['Resistência','desenergizado','A resistência deve ser medida em circuito desenergizado e isolado.'],['Isolação','megômetro','O megômetro é usado para avaliar resistência de isolamento.'],['Aterramento','ensaio','O ensaio avalia a resistência/impedância de dispersão.'],['Sequência de fases','sequencímetro','O instrumento identifica a ordem das fases.']].forEach(([a,s,r])=>add('Medições elétricas',a,s,`Para ${a}, qual procedimento/instrumento é adequado?`,[r,'Usar somente amperímetro','Ignorar a condição do circuito','Fazer sem registro','Substituir o projeto'],'A',r,E));
[['Unifilar','Representação','Uma linha simbólica pode representar um conjunto de condutores.'],['Multifilar','Representação','Os condutores são representados individualmente.'],['As built','Documentação','Registra a configuração efetivamente executada.'],['Diagrama de comando','Lógica','Representa a lógica de acionamento e controle.'],['Legenda','Simbologia','Explica símbolos e referências utilizados no desenho.'],['Identificação','Cabos','Permite relacionar fisicamente o cabo à documentação.']].forEach(([a,s,r])=>add('Desenho técnico',a,s,`Na documentação elétrica, ${a} significa:`,[r,'Documento financeiro','Relatório de custos','Medição de temperatura','Tipo de EPI'],'A',r,E));
/* situações práticas */
[['Recebimento','material','Conferir identificação, integridade, especificação e documentação.'],['Montagem','execução','Verificar execução contra projeto e procedimento aplicável.'],['Ensaio','resultado','Registrar instrumento, item, condição e resultado.'],['Não conformidade','desvio','Registrar o desvio e seguir o tratamento previsto.'],['Preservação','equipamento','Considerar ambiente e requisitos do fabricante/procedimento.'],['Liberação','critério','Liberar somente quando os requisitos aplicáveis forem atendidos/tratados.']].forEach(([a,s,r])=>add('Inspeção elétrica',a,s,`Durante ${a}, a conduta adequada é:`,[r,'Liberar automaticamente','Excluir registros','Ignorar projeto','Trocar qualquer componente sem análise'],'A',r,G));
window.INSPETOR_ELETRICA_EXPANSAO_BANK=Q;
})();