window.INSPETOR_PLANO_DETALHADO = [
{dia:'SEG',grupo:'Básica — Língua Portuguesa',topicos:[
'Compreensão global do texto','Localização de informações explícitas','Inferência de informações implícitas','Tema, finalidade e ideia principal','Relação entre partes do texto','Significação literal de palavras','Significação contextual de vocábulos','Sinônimos e antônimos pelo contexto','Coesão e referentes pronominais','Conectivos e relações de sentido'],q:25},
{dia:'TER',grupo:'Básica — Matemática I',topicos:[
'Teoria dos conjuntos: união, interseção, diferença e complemento','Diagramas de Venn','Proporção direta e inversa','Regra de três simples','Regra de três composta','Porcentagem e variação percentual','Média aritmética simples e ponderada','Função afim: gráfico, raiz e interpretação','Função quadrática: raízes, vértice e gráfico'],q:25},
{dia:'QUA',grupo:'Básica — Matemática II + Física',topicos:[
'Sistemas lineares 2x2 e 3x3','Trigonometria no triângulo retângulo','Seno, cosseno e tangente','Identidades trigonométricas fundamentais','Lei dos senos e lei dos cossenos','Resolução de triângulos','Geometria plana: áreas de polígonos','Geometria espacial: prismas e cilindros','Geometria espacial: pirâmides, cones e esferas','Geometria analítica: ponto e distância','Leis de Newton','Equilíbrio e torque','Energia mecânica e conservação','Cinemática básica: velocidade e aceleração','Dinâmica e trabalho'],q:30},
{dia:'QUI',grupo:'Específica Geral — Qualidade + Metrologia',topicos:[
'Conceitos de inspeção da qualidade','Controle de qualidade em recebimento','Controle durante a execução','Inspeção final','Não conformidade e tratamento','Registros da qualidade','Plano de inspeção e testes — ITP/PIT','ISO 9001:2000 — princípios e abordagem de processos','Documentação e evidências da qualidade','Metrologia: erro, incerteza e exatidão','Precisão, resolução e repetibilidade','Rastreabilidade metrológica','SI: grandezas e unidades','Algarismos significativos','Arredondamento','Conversão de unidades','Escalas e coordenadas'],q:30},
{dia:'SEX',grupo:'Específica Geral — Segurança + Física aplicada',topicos:[
'Perigos elétricos: choque, arco elétrico e queimaduras','Risco x perigo','EPI e EPC','Bloqueio e etiquetagem — conceitos','Trabalho desenergizado e verificação de ausência de tensão','Aterramento e equipotencialização — conceitos','Sinalização e isolamento de área','Permissão e liberação de trabalho','Atmosferas/áreas classificadas — noções','Princípios de prevenção de acidentes','Calor, dilatação e processos térmicos','Eletrostática','Corrente elétrica e cargas em movimento','Eletromagnetismo','Radiações eletromagnéticas','Hidrostática'],q:30},
{dia:'SAB',grupo:'Específica Elétrica I — Eletrotécnica',topicos:[
'Grandezas elétricas: tensão, corrente, resistência e potência','Lei de Ohm','Leis de Kirchhoff','Associação série e paralelo','Potência e energia elétrica','Circuitos CC','Circuitos CA senoidais','Valor médio e valor eficaz','Frequência, período e frequência angular','Fasores','Impedância e admitância','Reatância indutiva e capacitiva','Potência ativa, reativa e aparente','Fator de potência','Correção do fator de potência','Sistemas trifásicos','Ligação estrela e triângulo','Tensão de fase e de linha','Transformadores: relação de transformação','Indução eletromagnética','Curto-circuito e conceitos de proteção'],q:35},
{dia:'DOM',grupo:'Específica Elétrica II — Máquinas, Medições e Desenho',topicos:[
'Motores de indução trifásicos','Velocidade síncrona e escorregamento','Partida direta','Estrela-triângulo','Soft starter','Inversor de frequência','Contatores e relés','Disjuntores termomagnéticos','Fusíveis','DR e proteção diferencial','Medição de tensão com multímetro','Medição de corrente','Medição de resistência','Medição de resistência de isolamento com megômetro','Medição de resistência de aterramento','Calibração e rastreabilidade','Categoria de medição dos instrumentos','Leitura de diagrama unifilar','Diagramas de comando e força','Simbologia elétrica','Identificação de cabos e componentes','Interpretação de esquemas e desenhos técnicos'],q:50}
];