-- AprovaAI — estrutura inicial do painel administrativo
-- Execute este SQL no Supabase > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  status text not null default 'active' check (status in ('active','blocked','expired')),
  purchased_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, course_id)
);

create table if not exists public.user_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text,
  ip_address inet,
  user_agent text,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  active boolean not null default true,
  unique(user_id, device_id)
);

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.user_courses enable row level security;
alter table public.user_sessions enable row level security;

-- Função usada pelas políticas para verificar administrador sem depender de dados do frontend.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  );
$$;

-- Aluno pode consultar seu próprio perfil; administradores podem consultar todos.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Administrador possui acesso completo às tabelas administrativas.
drop policy if exists courses_admin_all on public.courses;
create policy courses_admin_all on public.courses
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists user_courses_admin_all on public.user_courses;
create policy user_courses_admin_all on public.user_courses
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists user_sessions_admin_all on public.user_sessions;
create policy user_sessions_admin_all on public.user_sessions
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- O próprio aluno pode consultar seus cursos.
drop policy if exists user_courses_self_select on public.user_courses;
create policy user_courses_self_select on public.user_courses
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

-- Cria perfil automaticamente no cadastro.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Depois de criar sua conta pelo site, promova seu usuário a administrador:
-- update public.profiles
-- set role = 'admin'
-- where id = 'COLE-AQUI-O-UUID-DO-SEU-USUARIO';

-- Cursos iniciais do AprovaAI.
insert into public.courses (name, slug, description)
values
  ('ACE Maricá', 'ace-marica', 'Agente de Combate às Endemias — Maricá/RJ.'),
  ('Transpetro', 'transpetro', 'Seleção de cargos e trilhas da Transpetro.'),
  ('Inspetor de Elétrica', 'inspetor-eletrica', 'Preparação para Inspetor de Elétrica.')
on conflict (slug) do nothing;
